package com.kakarote.crm9.erp.fbt.vo.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCheckDataHotelOrder<M extends BaseCheckDataHotelOrder<M>> extends Model<M> implements IBean {

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}
	
	public String getOrderId() {
		return getStr("order_id");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}
	
	public Integer getStatus() {
		return getInt("status");
	}

	public void setStatusName(String statusName) {
		set("status_name", statusName);
	}
	
	public String getStatusName() {
		return getStr("status_name");
	}

	public void setSupplierOrderId(String supplierOrderId) {
		set("supplier_order_id", supplierOrderId);
	}
	
	public String getSupplierName() {
		return getStr("supplier_name");
	}

	public void setSupplierName(String supplierName) {
		set("supplier_name", supplierName);
	}

	public String getSupplierOrderId() {
		return getStr("supplier_order_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setPersonalTotalPay(java.math.BigDecimal personalTotalPay) {
		set("personal_total_pay", personalTotalPay);
	}
	
	public java.math.BigDecimal getPersonalTotalPay() {
		return get("personal_total_pay");
	}

	public void setTotalPayPrice(java.math.BigDecimal totalPayPrice) {
		set("total_pay_price", totalPayPrice);
	}
	
	public java.math.BigDecimal getTotalPayPrice() {
		return get("total_pay_price");
	}

	public void setActualPrice(java.math.BigDecimal actualPrice) {
		set("actual_price", actualPrice);
	}
	
	public java.math.BigDecimal getActualPrice() {
		return get("actual_price");
	}

	public void setCustomerId(String customerId) {
		set("customer_id", customerId);
	}
	
	public String getCustomerId() {
		return getStr("customer_id");
	}

	public void setCustomerName(String customerName) {
		set("customer_name", customerName);
	}
	
	public String getCustomerName() {
		return getStr("customer_name");
	}

	public void setCustomerPhone(String customerPhone) {
		set("customer_phone", customerPhone);
	}
	
	public String getCustomerPhone() {
		return getStr("customer_phone");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setFullOrgUnit(String fullOrgUnit) {
		set("full_org_unit", fullOrgUnit);
	}
	
	public String getFullOrgUnit() {
		return getStr("full_org_unit");
	}

	public void setHotelName(String hotelName) {
		set("hotel_name", hotelName);
	}
	
	public String getHotelName() {
		return getStr("hotel_name");
	}

	public void setHotelPhone(String hotelPhone) {
		set("hotel_phone", hotelPhone);
	}
	
	public String getHotelPhone() {
		return getStr("hotel_phone");
	}

	public void setCheckinDate(java.util.Date checkinDate) {
		set("checkin_date", checkinDate);
	}
	
	public java.util.Date getCheckinDate() {
		return get("checkin_date");
	}

	public void setCheckoutDate(java.util.Date checkoutDate) {
		set("checkout_date", checkoutDate);
	}
	
	public java.util.Date getCheckoutDate() {
		return get("checkout_date");
	}

	public void setCityName(String cityName) {
		set("city_name", cityName);
	}
	
	public String getCityName() {
		return getStr("city_name");
	}

	public void setHotelAddress(String hotelAddress) {
		set("hotel_address", hotelAddress);
	}
	
	public String getHotelAddress() {
		return getStr("hotel_address");
	}

	public void setRoomType(String roomType) {
		set("room_type", roomType);
	}
	
	public String getRoomType() {
		return getStr("room_type");
	}

	public void setDeal(Integer deal) {
		set("deal", deal);
	}
	
	public Integer getDeal() {
		return getInt("deal");
	}

}
