package com.kakarote.crm9.erp.fbt.vo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCheckDataPermission<M extends BaseCheckDataPermission<M>> extends Model<M> implements IBean {

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public void setUserName(String userName) {
		set("userName", userName);
	}
	
	public String getUserName() {
		return getStr("userName");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}
	
	public Integer getLevel() {
		return getInt("level");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
