package com.kakarote.crm9.erp.ione.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsIoneUserInfo<M extends BaseWxcmsIoneUserInfo<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	public java.lang.String getUuid() {
		return getStr("uuid");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public void setMcuId(java.lang.String mcuId) {
		set("mcu_id", mcuId);
	}
	
	public java.lang.String getMcuId() {
		return getStr("mcu_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setCreateUserUuid(java.lang.String createUserUuid) {
		set("create_user_uuid", createUserUuid);
	}
	
	public java.lang.String getCreateUserUuid() {
		return getStr("create_user_uuid");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModiUserUuid(java.lang.String modiUserUuid) {
		set("modi_user_uuid", modiUserUuid);
	}
	
	public java.lang.String getModiUserUuid() {
		return getStr("modi_user_uuid");
	}

	public void setModiDate(java.util.Date modiDate) {
		set("modi_date", modiDate);
	}
	
	public java.util.Date getModiDate() {
		return get("modi_date");
	}

	public void setOriOpenId(java.lang.String oriOpenId) {
		set("ori_open_id", oriOpenId);
	}
	
	public java.lang.String getOriOpenId() {
		return getStr("ori_open_id");
	}

}
