package com.kakarote.crm9.erp.jxc.entity;

import com.kakarote.crm9.erp.jxc.entity.base.BaseJxcOrderDelivery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JxcOrderDelivery extends BaseJxcOrderDelivery<JxcOrderDelivery> {
	public static final JxcOrderDelivery dao = new JxcOrderDelivery().dao();
}
