package com.kakarote.crm9.erp.jxc.entity;


import com.kakarote.crm9.erp.jxc.entity.base.BaseJxcOrderReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JxcOrderReport extends BaseJxcOrderReport<JxcOrderReport> {
	public static final JxcOrderReport dao = new JxcOrderReport().dao();
}
