package com.kakarote.crm9.erp.jxc.entity;

import com.kakarote.crm9.erp.jxc.entity.base.BaseJxcOrderReportDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JxcOrderReportDetail extends BaseJxcOrderReportDetail<JxcOrderReportDetail> {
	public static final JxcOrderReportDetail dao = new JxcOrderReportDetail().dao();
}
