package com.kakarote.crm9.erp.jxc.entity;

import com.kakarote.crm9.erp.jxc.entity.base.BaseJxcOrderDeliveryCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JxcOrderDeliveryCode extends BaseJxcOrderDeliveryCode<JxcOrderDeliveryCode> {
	public static final JxcOrderDeliveryCode dao = new JxcOrderDeliveryCode().dao();
}
