package com.kakarote.crm9.erp.jxc.entity;


import com.kakarote.crm9.erp.jxc.entity.base.BaseJxcOrderMcuid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JxcOrderMcuid extends BaseJxcOrderMcuid<JxcOrderMcuid> {
	public static final JxcOrderMcuid dao = new JxcOrderMcuid().dao();
}
