package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanAreaRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanAreaRelation extends BaseHrGongdanAreaRelation<HrGongdanAreaRelation> {
	public static final HrGongdanAreaRelation dao = new HrGongdanAreaRelation().dao();
}
