package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanFjf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanFjf extends BaseHrGongdanFjf<HrGongdanFjf> {
	public static final HrGongdanFjf dao = new HrGongdanFjf().dao();
}
