package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanWsfLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanWsfLog extends BaseHrGongdanWsfLog<HrGongdanWsfLog> {
	public static final HrGongdanWsfLog dao = new HrGongdanWsfLog().dao();
}
