package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanYzjOvertime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanYzjOvertime extends BaseHrGongdanYzjOvertime<HrGongdanYzjOvertime> {
	public static final HrGongdanYzjOvertime dao = new HrGongdanYzjOvertime().dao();
}
