package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanRepair;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanRepair extends BaseHrGongdanRepair<HrGongdanRepair> {
	public static final HrGongdanRepair dao = new HrGongdanRepair().dao();
}
