package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanHistory extends BaseHrGongdanHistory<HrGongdanHistory> {
	public static final HrGongdanHistory dao = new HrGongdanHistory().dao();
}
