package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanBook extends BaseHrGongdanBook<HrGongdanBook> {
	public static final HrGongdanBook dao = new HrGongdanBook().dao();
}
