package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanYzjOvertimeDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanYzjOvertimeDetail extends BaseHrGongdanYzjOvertimeDetail<HrGongdanYzjOvertimeDetail> {
	public static final HrGongdanYzjOvertimeDetail dao = new HrGongdanYzjOvertimeDetail().dao();
}
