package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanWdtTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanWdtTrade extends BaseHrGongdanWdtTrade<HrGongdanWdtTrade> {
	public static final HrGongdanWdtTrade dao = new HrGongdanWdtTrade().dao();
}
