package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanFinanceFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanFinanceFee extends BaseHrGongdanFinanceFee<HrGongdanFinanceFee> {
	public static final HrGongdanFinanceFee dao = new HrGongdanFinanceFee().dao();
}
