package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanSabLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanSabLog extends BaseHrGongdanSabLog<HrGongdanSabLog> {
	public static final HrGongdanSabLog dao = new HrGongdanSabLog().dao();
}
