package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanHistoryWsf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanHistoryWsf extends BaseHrGongdanHistoryWsf<HrGongdanHistoryWsf> {
	public static final HrGongdanHistoryWsf dao = new HrGongdanHistoryWsf().dao();
}
