package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanLog extends BaseHrGongdanLog<HrGongdanLog> {
	public static final HrGongdanLog dao = new HrGongdanLog().dao();
}
