package com.kakarote.crm9.erp.yeyx.entity;
import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanZmnLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanZmnLog extends BaseHrGongdanZmnLog<HrGongdanZmnLog> {
	public static final HrGongdanZmnLog dao = new HrGongdanZmnLog().dao();
}
