package com.kakarote.crm9.erp.yeyx.entity;

import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdan extends BaseHrGongdan<HrGongdan> {
	public static final HrGongdan dao = new HrGongdan().dao();
}
