package com.kakarote.crm9.erp.yeyx.entity;


import com.kakarote.crm9.erp.yeyx.entity.base.BaseHrGongdanWdtTradeGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanWdtTradeGoods extends BaseHrGongdanWdtTradeGoods<HrGongdanWdtTradeGoods> {
	public static final HrGongdanWdtTradeGoods dao = new HrGongdanWdtTradeGoods().dao();
}
