package com.kakarote.crm9.erp.finance.vo;

import com.kakarote.crm9.erp.finance.vo.base.BaseHrGongdanFinanceCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanFinanceCharge extends BaseHrGongdanFinanceCharge<HrGongdanFinanceCharge> {
	public static final HrGongdanFinanceCharge dao = new HrGongdanFinanceCharge().dao();
}
