package com.kakarote.crm9.erp.finance.entity;

import com.kakarote.crm9.erp.finance.entity.base.BaseHrGongdanFinanceChargeService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrGongdanFinanceChargeService extends BaseHrGongdanFinanceChargeService<HrGongdanFinanceChargeService> {
	public static final HrGongdanFinanceChargeService dao = new HrGongdanFinanceChargeService().dao();
}
