package com.kakarote.crm9.erp.ione.entity;

import com.kakarote.crm9.erp.ione.entity.base.BaseWxcmsIoneUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsIoneUserInfo extends BaseWxcmsIoneUserInfo<WxcmsIoneUserInfo> {
	public static final WxcmsIoneUserInfo dao = new WxcmsIoneUserInfo().dao();
}
