package com.kakarote.crm9.erp.ione.entity;

import com.kakarote.crm9.erp.ione.entity.base.BaseWxcmsIoneWarrantyCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsIoneWarrantyCard extends BaseWxcmsIoneWarrantyCard<WxcmsIoneWarrantyCard> {
	public static final WxcmsIoneWarrantyCard dao = new WxcmsIoneWarrantyCard().dao();
}
