package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseHrRegister;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrRegister extends BaseHrRegister<HrRegister> {
	public static final HrRegister dao = new HrRegister().dao();
}
