package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortEmp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortEmp extends BasePortEmp<PortEmp> {
	public static final PortEmp dao = new PortEmp().dao();
}
