package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortDept extends BasePortDept<PortDept> {
	public static final PortDept dao = new PortDept().dao();
}
