package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityHelper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityHelper extends BasePortActivityHelper<PortActivityHelper> {
	public static final PortActivityHelper dao = new PortActivityHelper().dao();
}
