package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityPlaybill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityPlaybill extends BasePortActivityPlaybill<PortActivityPlaybill> {
	public static final PortActivityPlaybill dao = new PortActivityPlaybill().dao();
}
