package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityEnroll;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityEnroll extends BasePortActivityEnroll<PortActivityEnroll> {
	public static final PortActivityEnroll dao = new PortActivityEnroll().dao();
}
