package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityAddress extends BasePortActivityAddress<PortActivityAddress> {
	public static final PortActivityAddress dao = new PortActivityAddress().dao();
}
