package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivity extends BasePortActivity<PortActivity> {
	public static final PortActivity dao = new PortActivity().dao();
}
