package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityEmp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityEmp extends BasePortActivityEmp<PortActivityEmp> {
	public static final PortActivityEmp dao = new PortActivityEmp().dao();
}
