package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityShare extends BasePortActivityShare<PortActivityShare> {
	public static final PortActivityShare dao = new PortActivityShare().dao();
}
