package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortActivityAssist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortActivityAssist extends BasePortActivityAssist<PortActivityAssist> {
	public static final PortActivityAssist dao = new PortActivityAssist().dao();
}
