package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BasePortEmpRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortEmpRelation extends BasePortEmpRelation<PortEmpRelation> {
	public static final PortEmpRelation dao = new PortEmpRelation().dao();
}
