package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseRegist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Regist extends BaseRegist<Regist> {
	public static final Regist dao = new Regist().dao();
}
