package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseSysEnummain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysEnummain extends BaseSysEnummain<SysEnummain> {
	public static final SysEnummain dao = new SysEnummain().dao();
}
