package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseSysSftable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSftable extends BaseSysSftable<SysSftable> {

	public static final SysSftable dao = new SysSftable().dao();
}
