package com.kakarote.crm9.erp.wxcms.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsActivityLottery<M extends BaseWxcmsActivityLottery<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setAcId(String acId) {
		set("ac_id", acId);
	}

	public String getAcId() {
		return getStr("ac_id");
	}

	public void setOpenId(String openId) {
		set("open_id", openId);
	}
	
	public String getOpenId() {
		return getStr("open_id");
	}

	public void setWinOrNot(String winOrNot) {
		set("win_or_not", winOrNot);
	}
	
	public String getWinOrNot() {
		return getStr("win_or_not");
	}

	public void setPrize(String prize) {
		set("prize", prize);
	}
	
	public String getPrize() {
		return getStr("prize");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
