package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountAgentShop<M extends BaseWxcmsAccountAgentShop<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setAgentId(String agentId) {
		set("agent_id", agentId);
	}
	
	public String getAgentId() {
		return getStr("agent_id");
	}

	public void setShopid(Long shopid) {
		set("shopid", shopid);
	}
	
	public Long getShopid() {
		return getLong("shopid");
	}

}
