package com.kakarote.crm9.erp.wxcms.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountShop<M extends BaseWxcmsAccountShop<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setQrcodeParam(String qrcodeParam) {
		set("qrcode_param", qrcodeParam);
	}
	
	public String getQrcodeParam() {
		return getStr("qrcode_param");
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
	}
	
	public String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setProvince(String province) {
		set("province", province);
	}
	
	public String getProvince() {
		return getStr("province");
	}

	public void setCity(String city) {
		set("city", city);
	}
	
	public String getCity() {
		return getStr("city");
	}

	public void setDistrict(String district) {
		set("district", district);
	}
	
	public String getDistrict() {
		return getStr("district");
	}

	public void setProvinceId(String provinceId) {
		set("provinceId", provinceId);
	}
	
	public String getProvinceId() {
		return getStr("provinceId");
	}

	public void setCityId(String cityId) {
		set("cityId", cityId);
	}
	
	public String getCityId() {
		return getStr("cityId");
	}

	public void setDistrictId(String districtId) {
		set("districtId", districtId);
	}
	
	public String getDistrictId() {
		return getStr("districtId");
	}

	public void setManager(String manager) {
		set("manager", manager);
	}
	
	public String getManager() {
		return getStr("manager");
	}

	public void setAgentName(String agentName) {
		set("agentName", agentName);
	}
	
	public String getAgentName() {
		return getStr("agentName");
	}

	public void setAgentPhone(String agentPhone) {
		set("agentPhone", agentPhone);
	}
	
	public String getAgentPhone() {
		return getStr("agentPhone");
	}

	public void setMarkingType(String markingType) {
		set("markingType", markingType);
	}
	
	public String getMarkingType() {
		return getStr("markingType");
	}

	public void setAddress(String address) {
		set("address", address);
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public void setEmployeeNumber(Integer employeeNumber) {
		set("employeeNumber", employeeNumber);
	}
	
	public Integer getEmployeeNumber() {
		return getInt("employeeNumber");
	}

	public void setYearSaleTarget(Integer yearSaleTarget) {
		set("yearSaleTarget", yearSaleTarget);
	}
	
	public Integer getYearSaleTarget() {
		return getInt("yearSaleTarget");
	}

	public void setDoorHearWidth(Integer doorHearWidth) {
		set("doorHearWidth", doorHearWidth);
	}
	
	public Integer getDoorHearWidth() {
		return getInt("doorHearWidth");
	}

	public void setArea(Integer area) {
		set("area", area);
	}
	
	public Integer getArea() {
		return getInt("area");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}
	
	public Integer getLevel() {
		return getInt("level");
	}

	public void setOpenTime(String openTime) {
		set("openTime", openTime);
	}
	
	public String getOpenTime() {
		return getStr("openTime");
	}

	public void setShopNo(String shopNo) {
		set("shopNo", shopNo);
	}
	
	public String getShopNo() {
		return getStr("shopNo");
	}

	public void setAgentNo(String agentNo) {
		set("agentNo", agentNo);
	}
	
	public String getAgentNo() {
		return getStr("agentNo");
	}

	public void setOperatingStatus(Integer operatingStatus) {
		set("operatingStatus", operatingStatus);
	}
	
	public Integer getOperatingStatus() {
		return getInt("operatingStatus");
	}

	public void setStore(Integer store) {
		set("store", store);
	}
	
	public Integer getStore() {
		return getInt("store");
	}

	public void setIsValid(Integer isValid) {
		set("is_valid", isValid);
	}
	
	public Integer getIsValid() {
		return getInt("is_valid");
	}

}
