package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountQrcodeFans<M extends BaseWxcmsAccountQrcodeFans<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setFromuserName(String fromuserName) {
		set("fromuser_name", fromuserName);
	}
	
	public String getFromuserName() {
		return getStr("fromuser_name");
	}

	public void setAgentId(String agentId) {
		set("agent_id", agentId);
	}
	
	public String getAgentId() {
		return getStr("agent_id");
	}

	public void setEventKey(String eventKey) {
		set("event_key", eventKey);
	}
	
	public String getEventKey() {
		return getStr("event_key");
	}

	public void setTouserName(String touserName) {
		set("touser_name", touserName);
	}
	
	public String getTouserName() {
		return getStr("touser_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setFansLevel(Integer fansLevel) {
		set("fans_level", fansLevel);
	}
	
	public Integer getFansLevel() {
		return getInt("fans_level");
	}

	public void setStore(Integer store) {
		set("store", store);
	}
	
	public Integer getStore() {
		return getInt("store");
	}

	public void setIsLocation(Integer isLocation) {
		set("isLocation", isLocation);
	}
	
	public Integer getIsLocation() {
		return getInt("isLocation");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

}
