package com.kakarote.crm9.erp.wxcms.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountShopQrcode<M extends BaseWxcmsAccountShopQrcode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setShopId(Long shopId) {
		set("shop_id", shopId);
	}
	
	public Long getShopId() {
		return getLong("shop_id");
	}

	public void setQrcodeParam(String qrcodeParam) {
		set("qrcode_param", qrcodeParam);
	}
	
	public String getQrcodeParam() {
		return getStr("qrcode_param");
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
	}
	
	public String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
