package com.kakarote.crm9.erp.wxcms.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsCompetitive<M extends BaseWxcmsCompetitive<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}
	
	public String getBrand() {
		return getStr("brand");
	}

	public void setProduct(String product) {
		set("product", product);
	}
	
	public String getProduct() {
		return getStr("product");
	}

	public void setPrice(String price) {
		set("price", price);
	}
	
	public String getPrice() {
		return getStr("price");
	}

	public void setAdvantage(String advantage) {
		set("advantage", advantage);
	}
	
	public String getAdvantage() {
		return getStr("advantage");
	}

	public void setDisadvantage(String disadvantage) {
		set("disadvantage", disadvantage);
	}
	
	public String getDisadvantage() {
		return getStr("disadvantage");
	}

	public void setPic(String pic) {
		set("pic", pic);
	}
	
	public String getPic() {
		return getStr("pic");
	}

	public void setPriceRange(String priceRange) {
		set("priceRange", priceRange);
	}
	
	public String getPriceRange() {
		return getStr("priceRange");
	}

	public void setMarketObstacles(String marketObstacles) {
		set("marketObstacles", marketObstacles);
	}
	
	public String getMarketObstacles() {
		return getStr("marketObstacles");
	}

}
