package com.kakarote.crm9.erp.wxcms.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsFluCode<M extends BaseWxcmsFluCode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setNewSystem(String newSystem) {
		set("newSystem", newSystem);
	}
	
	public String getNewSystem() {
		return getStr("newSystem");
	}

	public void setOldSystem(String oldSystem) {
		set("oldSystem", oldSystem);
	}
	
	public String getOldSystem() {
		return getStr("oldSystem");
	}

}
