package com.kakarote.crm9.erp.wxcms.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountTeamQrcode<M extends BaseWxcmsAccountTeamQrcode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setQrcodeParam(String qrcodeParam) {
		set("qrcode_param", qrcodeParam);
	}
	
	public String getQrcodeParam() {
		return getStr("qrcode_param");
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
	}
	
	public String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

}
