package com.kakarote.crm9.erp.yeyx.entity.vo;


import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Data
public class HrGongdanRepairRequest {
    /**
     * id
     */
    private Long id;
    /**
     * 报修单号
     */
    private String orderNumber;
    /**
     * 联系人
     */
    private String contact;

    /**
     * 联系电话
     */
    private String phone;

    /**
     * 预约日期
     */
    private String bookDate;

    /**
     * 地址
     */
    private String address;
    /**
     * 购买型号
     */
    private String buyType;
    /**
     * 设备SN码
     */
    private String equipSNCode;
    /**
     * 拍照上传图片
     */
    private String photo;
    /**
     * 故障描述
     */
    private String remark;
    /**
     * 提交人openId
     */
    private String open_id;
    /**
     * 是否生成工单 1-是；0-不是
     */
    private Integer is_generate;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss",iso= DateTimeFormat.ISO.DATE_TIME)
    private Date create_time;

    private BigDecimal standardFee;

    private BigDecimal adjustmentFee;

    private Integer payType;

    private Integer sourceType;

    private String productColor;
    private String productType;
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd",iso= DateTimeFormat.ISO.DATE)
    private Date productActivationDate;
}
