package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMessage extends BaseAdminMessage<AdminMessage> {
	public static final AdminMessage dao = new AdminMessage().dao();
}
