package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmArea extends BaseCrmArea<CrmArea> {
	public static final CrmArea dao = new CrmArea().dao();
}
