package com.kakarote.crm9.erp.jxc.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJxcOrderMcuid<M extends BaseJxcOrderMcuid<M>> extends Model<M> implements IBean {

	public void setMcuid(String mcuid) {
		set("mcuid", mcuid);
	}
	
	public String getMcuid() {
		return getStr("mcuid");
	}

	public void setZt(String zt) {
		set("zt", zt);
	}
	
	public String getZt() {
		return getStr("zt");
	}

}
