package com.kakarote.crm9.erp.jxc.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJxcOrderDelivery<M extends BaseJxcOrderDelivery<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setDocno(String docno) {
		set("docno", docno);
	}
	
	public String getDocno() {
		return getStr("docno");
	}

	public void setCustomer(String customer) {
		set("customer", customer);
	}
	
	public String getCustomer() {
		return getStr("customer");
	}

	public void setNum(Integer num) {
		set("num", num);
	}
	
	public Integer getNum() {
		return getInt("num");
	}

	public void setDealTime(java.util.Date dealTime) {
		set("deal_time", dealTime);
	}
	
	public java.util.Date getDealTime() {
		return get("deal_time");
	}

	public void setOrderNo(String orderNo) {
		set("order_no", orderNo);
	}
	
	public String getOrderNo() {
		return getStr("order_no");
	}

	public void setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
	}
	
	public Integer getOrderNum() {
		return getInt("order_num");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}
	
	public java.util.Date getOrderTime() {
		return get("order_time");
	}

}
