package com.kakarote.crm9.erp.jxc.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJxcOrderReportDetail<M extends BaseJxcOrderReportDetail<M>> extends Model<M> implements IBean {

	public void setOID(Integer OID) {
		set("OID", OID);
	}
	
	public Integer getOID() {
		return getInt("OID");
	}

	public void setMcuid(String mcuid) {
		set("mcuid", mcuid);
	}
	
	public String getMcuid() {
		return getStr("mcuid");
	}

	public void setCreateTime(String createTime) {
		set("createTime", createTime);
	}
	
	public String getCreateTime() {
		return getStr("createTime");
	}

	public void setReportNumber(String reportNumber) {
		set("reportNumber", reportNumber);
	}
	
	public String getReportNumber() {
		return getStr("reportNumber");
	}

	public void setRefPK(String RefPK) {
		set("RefPK", RefPK);
	}
	
	public String getRefPK() {
		return getStr("RefPK");
	}

	public void setFID(Integer FID) {
		set("FID", FID);
	}
	
	public Integer getFID() {
		return getInt("FID");
	}

	public void setRDT(String RDT) {
		set("RDT", RDT);
	}
	
	public String getRDT() {
		return getStr("RDT");
	}

	public void setRec(String Rec) {
		set("Rec", Rec);
	}
	
	public String getRec() {
		return getStr("Rec");
	}

	public void setReportId(String reportId) {
		set("reportId", reportId);
	}
	
	public String getReportId() {
		return getStr("reportId");
	}

}
