package com.kakarote.crm9.erp.jxc.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJxcOrderReport<M extends BaseJxcOrderReport<M>> extends Model<M> implements IBean {

	public void setOID(Integer OID) {
		set("OID", OID);
	}
	
	public Integer getOID() {
		return getInt("OID");
	}

	public void setReportNumber(String reportNumber) {
		set("reportNumber", reportNumber);
	}
	
	public String getReportNumber() {
		return getStr("reportNumber");
	}

	public void setOrderNumber(String orderNumber) {
		set("orderNumber", orderNumber);
	}
	
	public String getOrderNumber() {
		return getStr("orderNumber");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setTotalFee(java.math.BigDecimal totalFee) {
		set("totalFee", totalFee);
	}
	
	public java.math.BigDecimal getTotalFee() {
		return get("totalFee");
	}

	public void setTeamNo(String teamNo) {
		set("teamNo", teamNo);
	}
	
	public String getTeamNo() {
		return getStr("teamNo");
	}

	public void setCreateTime(String createTime) {
		set("createTime", createTime);
	}
	
	public String getCreateTime() {
		return getStr("createTime");
	}

	public void setRDT(String RDT) {
		set("RDT", RDT);
	}
	
	public String getRDT() {
		return getStr("RDT");
	}

	public void setTitle(String Title) {
		set("Title", Title);
	}
	
	public String getTitle() {
		return getStr("Title");
	}

	public void setFID(Integer FID) {
		set("FID", FID);
	}
	
	public Integer getFID() {
		return getInt("FID");
	}

	public void setCDT(String CDT) {
		set("CDT", CDT);
	}
	
	public String getCDT() {
		return getStr("CDT");
	}

	public void setRec(String Rec) {
		set("Rec", Rec);
	}
	
	public String getRec() {
		return getStr("Rec");
	}

	public void setEmps(String Emps) {
		set("Emps", Emps);
	}
	
	public String getEmps() {
		return getStr("Emps");
	}

	public void setFkDept(String fkDept) {
		set("FK_Dept", fkDept);
	}
	
	public String getFkDept() {
		return getStr("FK_Dept");
	}

	public void setFkNy(String fkNy) {
		set("FK_NY", fkNy);
	}
	
	public String getFkNy() {
		return getStr("FK_NY");
	}

	public void setMyNum(Integer MyNum) {
		set("MyNum", MyNum);
	}
	
	public Integer getMyNum() {
		return getInt("MyNum");
	}

	public void setHandlerUrlt(String handlerUrlt) {
		set("Handler_URLT", handlerUrlt);
	}
	
	public String getHandlerUrlt() {
		return getStr("Handler_URLT");
	}

	public void setHandlerHandlerempst(String handlerHandlerempst) {
		set("Handler_HandlerEmpsT", handlerHandlerempst);
	}
	
	public String getHandlerHandlerempst() {
		return getStr("Handler_HandlerEmpsT");
	}

	public void setPNodeID(Integer PNodeID) {
		set("PNodeID", PNodeID);
	}
	
	public Integer getPNodeID() {
		return getInt("PNodeID");
	}

	public void setGUID(String GUID) {
		set("GUID", GUID);
	}
	
	public String getGUID() {
		return getStr("GUID");
	}

	public void setPEmp(String PEmp) {
		set("PEmp", PEmp);
	}
	
	public String getPEmp() {
		return getStr("PEmp");
	}

	public void setPrjNo(String PrjNo) {
		set("PrjNo", PrjNo);
	}
	
	public String getPrjNo() {
		return getStr("PrjNo");
	}

	public void setAtPara(String AtPara) {
		set("AtPara", AtPara);
	}
	
	public String getAtPara() {
		return getStr("AtPara");
	}

	public void setBillNo(String BillNo) {
		set("BillNo", BillNo);
	}
	
	public String getBillNo() {
		return getStr("BillNo");
	}

	public void setPrjName(String PrjName) {
		set("PrjName", PrjName);
	}
	
	public String getPrjName() {
		return getStr("PrjName");
	}

	public void setFlowNote(String FlowNote) {
		set("FlowNote", FlowNote);
	}
	
	public String getFlowNote() {
		return getStr("FlowNote");
	}

	public void setWFSta(Integer WFSta) {
		set("WFSta", WFSta);
	}
	
	public Integer getWFSta() {
		return getInt("WFSta");
	}

	public void setPWorkID(Integer PWorkID) {
		set("PWorkID", PWorkID);
	}
	
	public Integer getPWorkID() {
		return getInt("PWorkID");
	}

	public void setFlowDaySpan(java.math.BigDecimal FlowDaySpan) {
		set("FlowDaySpan", FlowDaySpan);
	}
	
	public java.math.BigDecimal getFlowDaySpan() {
		return get("FlowDaySpan");
	}

	public void setFlowEndNode(Integer FlowEndNode) {
		set("FlowEndNode", FlowEndNode);
	}
	
	public Integer getFlowEndNode() {
		return getInt("FlowEndNode");
	}

	public void setFlowEnderRDT(String FlowEnderRDT) {
		set("FlowEnderRDT", FlowEnderRDT);
	}
	
	public String getFlowEnderRDT() {
		return getStr("FlowEnderRDT");
	}

	public void setFlowStartRDT(String FlowStartRDT) {
		set("FlowStartRDT", FlowStartRDT);
	}
	
	public String getFlowStartRDT() {
		return getStr("FlowStartRDT");
	}

	public void setPFlowNo(String PFlowNo) {
		set("PFlowNo", PFlowNo);
	}
	
	public String getPFlowNo() {
		return getStr("PFlowNo");
	}

	public void setFlowEmps(String FlowEmps) {
		set("FlowEmps", FlowEmps);
	}
	
	public String getFlowEmps() {
		return getStr("FlowEmps");
	}

	public void setWFState(Integer WFState) {
		set("WFState", WFState);
	}
	
	public Integer getWFState() {
		return getInt("WFState");
	}

	public void setFlowEnder(String FlowEnder) {
		set("FlowEnder", FlowEnder);
	}
	
	public String getFlowEnder() {
		return getStr("FlowEnder");
	}

	public void setFlowStarter(String FlowStarter) {
		set("FlowStarter", FlowStarter);
	}
	
	public String getFlowStarter() {
		return getStr("FlowStarter");
	}

}
