package com.kakarote.crm9.erp.jxc.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJxcOrderDeliveryCode<M extends BaseJxcOrderDeliveryCode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setOrderNo(String orderNo) {
		set("order_no", orderNo);
	}
	
	public String getOrderNo() {
		return getStr("order_no");
	}

	public void setDocno(String docno) {
		set("docno", docno);
	}
	
	public String getDocno() {
		return getStr("docno");
	}

	public void setCode(String code) {
		set("code", code);
	}
	
	public String getCode() {
		return getStr("code");
	}

	public void setColor(String color) {
		set("color", color);
	}
	
	public String getColor() {
		return getStr("color");
	}

	public void setModel(String model) {
		set("model", model);
	}
	
	public String getModel() {
		return getStr("model");
	}

	public void setZt(Integer zt) {
		set("zt", zt);
	}
	
	public Integer getZt() {
		return getInt("zt");
	}

	public void setCustomer(String customer) {
		set("customer", customer);
	}
	
	public String getCustomer() {
		return getStr("customer");
	}

}
