package com.kakarote.crm9.erp.wxcms.entity;


import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsActivityCouponRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsActivityCouponRecord extends BaseWxcmsActivityCouponRecord<WxcmsActivityCouponRecord> {
	public static final WxcmsActivityCouponRecord dao = new WxcmsActivityCouponRecord().dao();
}
