package com.kakarote.crm9.erp.wxcms.entity;

import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsActivityCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsActivityCoupon extends BaseWxcmsActivityCoupon<WxcmsActivityCoupon> {
	public static final WxcmsActivityCoupon dao = new WxcmsActivityCoupon().dao();
}
