package com.kakarote.crm9.erp.wxcms.entity;

import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsAccountQrcodeFans;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountQrcodeFans extends BaseWxcmsAccountQrcodeFans<WxcmsAccountQrcodeFans> {
	public static final WxcmsAccountQrcodeFans dao = new WxcmsAccountQrcodeFans().dao();
}
