package com.kakarote.crm9.erp.wxcms.entity;

import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsAccountShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountShop extends BaseWxcmsAccountShop<WxcmsAccountShop> {
	public static final WxcmsAccountShop dao = new WxcmsAccountShop().dao();
}
