package com.kakarote.crm9.erp.wxcms.entity;


import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsActivityLottery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsActivityLottery extends BaseWxcmsActivityLottery<WxcmsActivityLottery> {
	public static final WxcmsActivityLottery dao = new WxcmsActivityLottery().dao();
}
