package com.kakarote.crm9.erp.wxcms.entity;


import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsFluCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsFluCode extends BaseWxcmsFluCode<WxcmsFluCode> {
	public static final WxcmsFluCode dao = new WxcmsFluCode().dao();
}
