package com.kakarote.crm9.erp.wxcms.entity;


import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsActivityEnroll;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsActivityEnroll extends BaseWxcmsActivityEnroll<WxcmsActivityEnroll> {
	public static final WxcmsActivityEnroll dao = new WxcmsActivityEnroll().dao();
}
