package com.kakarote.crm9.erp.wxcms.entity;
import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsCompetitive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsCompetitive extends BaseWxcmsCompetitive<WxcmsCompetitive> {
	public static final WxcmsCompetitive dao = new WxcmsCompetitive().dao();
}
