package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountAgent extends BaseWxcmsAccountAgent<WxcmsAccountAgent> {
	public static final WxcmsAccountAgent dao = new WxcmsAccountAgent().dao();
}
