package com.kakarote.crm9.erp.wxcms.entity;
import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsCompetitiveNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsCompetitiveNews extends BaseWxcmsCompetitiveNews<WxcmsCompetitiveNews> {
	public static final WxcmsCompetitiveNews dao = new WxcmsCompetitiveNews().dao();
}
