package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountAgentQrcode extends BaseWxcmsAccountAgentQrcode<WxcmsAccountAgentQrcode> {
	public static final WxcmsAccountAgentQrcode dao = new WxcmsAccountAgentQrcode().dao();
}
