package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountAgentShop extends BaseWxcmsAccountAgentShop<WxcmsAccountAgentShop> {
	public static final WxcmsAccountAgentShop dao = new WxcmsAccountAgentShop().dao();
}
