package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountFans extends BaseWxcmsAccountFans<WxcmsAccountFans> {
	public static final WxcmsAccountFans dao = new WxcmsAccountFans().dao();
}
