package com.kakarote.crm9.erp.wxcms.entity;

import com.kakarote.crm9.erp.wxcms.entity.base.BaseWxcmsAccountTeamQrcode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountTeamQrcode extends BaseWxcmsAccountTeamQrcode<WxcmsAccountTeamQrcode> {
	public static final WxcmsAccountTeamQrcode dao = new WxcmsAccountTeamQrcode().dao();
}
