package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountShopQrcode extends BaseWxcmsAccountShopQrcode<WxcmsAccountShopQrcode> {
	public static final WxcmsAccountShopQrcode dao = new WxcmsAccountShopQrcode().dao();
}
