package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountQrcodeFans extends BaseWxcmsAccountQrcodeFans<WxcmsAccountQrcodeFans> {
	public static final WxcmsAccountQrcodeFans dao = new WxcmsAccountQrcodeFans().dao();
}
