package com.kakarote.crm9.erp.admin.entity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxcmsAccountShop extends BaseWxcmsAccountShop<WxcmsAccountShop> {
	public static final WxcmsAccountShop dao = new WxcmsAccountShop().dao();
}
