package com.erpsnow.erp;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminMessage<M extends BaseAdminMessage<M>> extends Model<M> implements IBean {

	public void setMessageId(java.lang.Long messageId) {
		set("message_id", messageId);
	}
	
	public java.lang.Long getMessageId() {
		return getLong("message_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setLabel(java.lang.Integer label) {
		set("label", label);
	}
	
	public java.lang.Integer getLabel() {
		return getInt("label");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setCreateUser(java.lang.Long createUser) {
		set("create_user", createUser);
	}
	
	public java.lang.Long getCreateUser() {
		return getLong("create_user");
	}

	public void setRecipientUser(java.lang.Long recipientUser) {
		set("recipient_user", recipientUser);
	}
	
	public java.lang.Long getRecipientUser() {
		return getLong("recipient_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIsRead(java.lang.Integer isRead) {
		set("is_read", isRead);
	}
	
	public java.lang.Integer getIsRead() {
		return getInt("is_read");
	}

	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}
	
	public java.util.Date getReadTime() {
		return get("read_time");
	}

}
