package com.erpsnow.erp;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmArea<M extends BaseCrmArea<M>> extends Model<M> implements IBean {

	public void setCodeId(java.lang.Integer codeId) {
		set("code_id", codeId);
	}
	
	public java.lang.Integer getCodeId() {
		return getInt("code_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}
	
	public java.lang.String getCityName() {
		return getStr("city_name");
	}

}
