package com.kakarote.crm9.erp.fbt.vo;

import com.kakarote.crm9.erp.fbt.vo.base.BaseCheckDataPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckDataPermission extends BaseCheckDataPermission<CheckDataPermission> {
	public static final CheckDataPermission dao = new CheckDataPermission().dao();
}
