package com.kakarote.crm9.erp.fbt.vo;
import com.kakarote.crm9.erp.fbt.vo.base.BaseCheckDataCarOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckDataCarOrder extends BaseCheckDataCarOrder<CheckDataCarOrder> {
	public static final CheckDataCarOrder dao = new CheckDataCarOrder().dao();
}
