package com.kakarote.crm9.erp.fbt.vo;


import com.kakarote.crm9.erp.fbt.vo.base.BaseCheckDataAnalysis2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckDataAnalysis2 extends BaseCheckDataAnalysis2<CheckDataAnalysis2> {
	public static final CheckDataAnalysis2 dao = new CheckDataAnalysis2().dao();
}
