package com.kakarote.crm9.erp.fbt.vo;

import com.kakarote.crm9.erp.fbt.vo.base.BaseCheckDataAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckDataAddress extends BaseCheckDataAddress<CheckDataAddress> {
	public static final CheckDataAddress dao = new CheckDataAddress().dao();
}
