package com.kakarote.crm9.erp.fbt.vo;
import com.kakarote.crm9.erp.fbt.vo.base.BaseCheckDataHotelOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckDataHotelOrder extends BaseCheckDataHotelOrder<CheckDataHotelOrder> {
	public static final CheckDataHotelOrder dao = new CheckDataHotelOrder().dao();
}
