package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanWdtTrade<M extends BaseHrGongdanWdtTrade<M>> extends Model<M> implements IBean {

	public void setTradeId(Integer tradeId) {
		set("trade_id", tradeId);
	}
	
	public Integer getTradeId() {
		return getInt("trade_id");
	}

	public void setTradeNo(String tradeNo) {
		set("trade_no", tradeNo);
	}
	
	public String getTradeNo() {
		return getStr("trade_no");
	}

	public void setPlatformId(Integer platformId) {
		set("platform_id", platformId);
	}
	
	public Integer getPlatformId() {
		return getInt("platform_id");
	}

	public void setShopNo(String shopNo) {
		set("shop_no", shopNo);
	}
	
	public String getShopNo() {
		return getStr("shop_no");
	}

	public void setShopName(String shopName) {
		set("shop_name", shopName);
	}
	
	public String getShopName() {
		return getStr("shop_name");
	}

	public void setShopRemark(String shopRemark) {
		set("shop_remark", shopRemark);
	}
	
	public String getShopRemark() {
		return getStr("shop_remark");
	}

	public void setWarehouseType(Integer warehouseType) {
		set("warehouse_type", warehouseType);
	}
	
	public Integer getWarehouseType() {
		return getInt("warehouse_type");
	}

	public void setWarehouseNo(String warehouseNo) {
		set("warehouse_no", warehouseNo);
	}
	
	public String getWarehouseNo() {
		return getStr("warehouse_no");
	}

	public void setSrcTids(String srcTids) {
		set("src_tids", srcTids);
	}
	
	public String getSrcTids() {
		return getStr("src_tids");
	}

	public void setTradeStatus(Integer tradeStatus) {
		set("trade_status", tradeStatus);
	}
	
	public Integer getTradeStatus() {
		return getInt("trade_status");
	}

	public void setConsignStatus(Integer consignStatus) {
		set("consign_status", consignStatus);
	}
	
	public Integer getConsignStatus() {
		return getInt("consign_status");
	}

	public void setTradeType(Integer tradeType) {
		set("trade_type", tradeType);
	}
	
	public Integer getTradeType() {
		return getInt("trade_type");
	}

	public void setDeliveryTerm(Integer deliveryTerm) {
		set("delivery_term", deliveryTerm);
	}
	
	public Integer getDeliveryTerm() {
		return getInt("delivery_term");
	}

	public void setFreezeReason(Integer freezeReason) {
		set("freeze_reason", freezeReason);
	}
	
	public Integer getFreezeReason() {
		return getInt("freeze_reason");
	}

	public void setRefundStatus(Integer refundStatus) {
		set("refund_status", refundStatus);
	}
	
	public Integer getRefundStatus() {
		return getInt("refund_status");
	}

	public void setFenxiaoType(Integer fenxiaoType) {
		set("fenxiao_type", fenxiaoType);
	}
	
	public Integer getFenxiaoType() {
		return getInt("fenxiao_type");
	}

	public void setFenxiaoNick(String fenxiaoNick) {
		set("fenxiao_nick", fenxiaoNick);
	}
	
	public String getFenxiaoNick() {
		return getStr("fenxiao_nick");
	}

	public void setTradeTime(java.util.Date tradeTime) {
		set("trade_time", tradeTime);
	}
	
	public java.util.Date getTradeTime() {
		return get("trade_time");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}
	
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setCustomerName(String customerName) {
		set("customer_name", customerName);
	}
	
	public String getCustomerName() {
		return getStr("customer_name");
	}

	public void setCustomerNo(String customerNo) {
		set("customer_no", customerNo);
	}
	
	public String getCustomerNo() {
		return getStr("customer_no");
	}

	public void setPayAccount(String payAccount) {
		set("pay_account", payAccount);
	}
	
	public String getPayAccount() {
		return getStr("pay_account");
	}

	public void setBuyerNick(String buyerNick) {
		set("buyer_nick", buyerNick);
	}
	
	public String getBuyerNick() {
		return getStr("buyer_nick");
	}

	public void setReceiverName(String receiverName) {
		set("receiver_name", receiverName);
	}
	
	public String getReceiverName() {
		return getStr("receiver_name");
	}

	public void setReceiverProvince(Integer receiverProvince) {
		set("receiver_province", receiverProvince);
	}
	
	public Integer getReceiverProvince() {
		return getInt("receiver_province");
	}

	public void setReceiverCity(Integer receiverCity) {
		set("receiver_city", receiverCity);
	}
	
	public Integer getReceiverCity() {
		return getInt("receiver_city");
	}

	public void setReceiverDistrict(Integer receiverDistrict) {
		set("receiver_district", receiverDistrict);
	}
	
	public Integer getReceiverDistrict() {
		return getInt("receiver_district");
	}

	public void setReceiverAddress(String receiverAddress) {
		set("receiver_address", receiverAddress);
	}
	
	public String getReceiverAddress() {
		return getStr("receiver_address");
	}

	public void setReceiverMobile(String receiverMobile) {
		set("receiver_mobile", receiverMobile);
	}
	
	public String getReceiverMobile() {
		return getStr("receiver_mobile");
	}

	public void setReceiverTelno(String receiverTelno) {
		set("receiver_telno", receiverTelno);
	}
	
	public String getReceiverTelno() {
		return getStr("receiver_telno");
	}

	public void setReceiverZip(String receiverZip) {
		set("receiver_zip", receiverZip);
	}
	
	public String getReceiverZip() {
		return getStr("receiver_zip");
	}

	public void setReceiverArea(String receiverArea) {
		set("receiver_area", receiverArea);
	}
	
	public String getReceiverArea() {
		return getStr("receiver_area");
	}

	public void setReceiverRing(String receiverRing) {
		set("receiver_ring", receiverRing);
	}
	
	public String getReceiverRing() {
		return getStr("receiver_ring");
	}

	public void setReceiverDtb(String receiverDtb) {
		set("receiver_dtb", receiverDtb);
	}
	
	public String getReceiverDtb() {
		return getStr("receiver_dtb");
	}

	public void setToDeliverTime(String toDeliverTime) {
		set("to_deliver_time", toDeliverTime);
	}
	
	public String getToDeliverTime() {
		return getStr("to_deliver_time");
	}

	public void setBadReason(Integer badReason) {
		set("bad_reason", badReason);
	}
	
	public Integer getBadReason() {
		return getInt("bad_reason");
	}

	public void setLogisticsId(Integer logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	public Integer getLogisticsId() {
		return getInt("logistics_id");
	}

	public void setLogisticsName(String logisticsName) {
		set("logistics_name", logisticsName);
	}
	
	public String getLogisticsName() {
		return getStr("logistics_name");
	}

	public void setLogisticsCode(String logisticsCode) {
		set("logistics_code", logisticsCode);
	}
	
	public String getLogisticsCode() {
		return getStr("logistics_code");
	}

	public void setLogisticsType(Integer logisticsType) {
		set("logistics_type", logisticsType);
	}
	
	public Integer getLogisticsType() {
		return getInt("logistics_type");
	}

	public void setLogisticsNo(String logisticsNo) {
		set("logistics_no", logisticsNo);
	}
	
	public String getLogisticsNo() {
		return getStr("logistics_no");
	}

	public void setShopId(Integer shopId) {
		set("shop_id", shopId);
	}
	
	public Integer getShopId() {
		return getInt("shop_id");
	}

	public void setWarehouseId(Integer warehouseId) {
		set("warehouse_id", warehouseId);
	}
	
	public Integer getWarehouseId() {
		return getInt("warehouse_id");
	}

	public void setCheckStep(Integer checkStep) {
		set("check_step", checkStep);
	}
	
	public Integer getCheckStep() {
		return getInt("check_step");
	}

	public void setUnmergeMask(Integer unmergeMask) {
		set("unmerge_mask", unmergeMask);
	}
	
	public Integer getUnmergeMask() {
		return getInt("unmerge_mask");
	}

	public void setDelayToTime(String delayToTime) {
		set("delay_to_time", delayToTime);
	}
	
	public String getDelayToTime() {
		return getStr("delay_to_time");
	}

	public void setCustomerType(Integer customerType) {
		set("customer_type", customerType);
	}
	
	public Integer getCustomerType() {
		return getInt("customer_type");
	}

	public void setCustomerId(String customerId) {
		set("customer_id", customerId);
	}
	
	public String getCustomerId() {
		return getStr("customer_id");
	}

	public void setReceiverCountry(Integer receiverCountry) {
		set("receiver_country", receiverCountry);
	}
	
	public Integer getReceiverCountry() {
		return getInt("receiver_country");
	}

	public void setPreChargeTime(String preChargeTime) {
		set("pre_charge_time", preChargeTime);
	}
	
	public String getPreChargeTime() {
		return getStr("pre_charge_time");
	}

	public void setIsPrevNotify(Integer isPrevNotify) {
		set("is_prev_notify", isPrevNotify);
	}
	
	public Integer getIsPrevNotify() {
		return getInt("is_prev_notify");
	}

	public void setNoteCount(Integer noteCount) {
		set("note_count", noteCount);
	}
	
	public Integer getNoteCount() {
		return getInt("note_count");
	}

	public void setBuyerMessageCount(Integer buyerMessageCount) {
		set("buyer_message_count", buyerMessageCount);
	}
	
	public Integer getBuyerMessageCount() {
		return getInt("buyer_message_count");
	}

	public void setCsRemarkCount(Integer csRemarkCount) {
		set("cs_remark_count", csRemarkCount);
	}
	
	public Integer getCsRemarkCount() {
		return getInt("cs_remark_count");
	}

	public void setCsRemarkChangeCount(Integer csRemarkChangeCount) {
		set("cs_remark_change_count", csRemarkChangeCount);
	}
	
	public Integer getCsRemarkChangeCount() {
		return getInt("cs_remark_change_count");
	}

	public void setDiscountChange(java.math.BigDecimal discountChange) {
		set("discount_change", discountChange);
	}
	
	public java.math.BigDecimal getDiscountChange() {
		return get("discount_change");
	}

	public void setTradePrepay(java.math.BigDecimal tradePrepay) {
		set("trade_prepay", tradePrepay);
	}
	
	public java.math.BigDecimal getTradePrepay() {
		return get("trade_prepay");
	}

	public void setPiAmount(java.math.BigDecimal piAmount) {
		set("pi_amount", piAmount);
	}
	
	public java.math.BigDecimal getPiAmount() {
		return get("pi_amount");
	}

	public void setOtherCost(java.math.BigDecimal otherCost) {
		set("other_cost", otherCost);
	}
	
	public java.math.BigDecimal getOtherCost() {
		return get("other_cost");
	}

	public void setVolume(java.math.BigDecimal volume) {
		set("volume", volume);
	}
	
	public java.math.BigDecimal getVolume() {
		return get("volume");
	}

	public void setSalesScore(String salesScore) {
		set("sales_score", salesScore);
	}
	
	public String getSalesScore() {
		return getStr("sales_score");
	}

	public void setFlagId(Integer flagId) {
		set("flag_id", flagId);
	}
	
	public Integer getFlagId() {
		return getInt("flag_id");
	}

	public void setIsSealed(Integer isSealed) {
		set("is_sealed", isSealed);
	}
	
	public Integer getIsSealed() {
		return getInt("is_sealed");
	}

	public void setGiftMask(Integer giftMask) {
		set("gift_mask", giftMask);
	}
	
	public Integer getGiftMask() {
		return getInt("gift_mask");
	}

	public void setSplitFromTradeId(String splitFromTradeId) {
		set("split_from_trade_id", splitFromTradeId);
	}
	
	public String getSplitFromTradeId() {
		return getStr("split_from_trade_id");
	}

	public void setLogisticsTemplateId(String logisticsTemplateId) {
		set("logistics_template_id", logisticsTemplateId);
	}
	
	public String getLogisticsTemplateId() {
		return getStr("logistics_template_id");
	}

	public void setSendbillTemplateId(String sendbillTemplateId) {
		set("sendbill_template_id", sendbillTemplateId);
	}
	
	public String getSendbillTemplateId() {
		return getStr("sendbill_template_id");
	}

	public void setRevertReason(Integer revertReason) {
		set("revert_reason", revertReason);
	}
	
	public Integer getRevertReason() {
		return getInt("revert_reason");
	}

	public void setCancelReason(Integer cancelReason) {
		set("cancel_reason", cancelReason);
	}
	
	public Integer getCancelReason() {
		return getInt("cancel_reason");
	}

	public void setIsUnpaymentSms(Integer isUnpaymentSms) {
		set("is_unpayment_sms", isUnpaymentSms);
	}
	
	public Integer getIsUnpaymentSms() {
		return getInt("is_unpayment_sms");
	}

	public void setPackageId(String packageId) {
		set("package_id", packageId);
	}
	
	public String getPackageId() {
		return getStr("package_id");
	}

	public void setTradeMask(String tradeMask) {
		set("trade_mask", tradeMask);
	}
	
	public String getTradeMask() {
		return getStr("trade_mask");
	}

	public void setReserve(String reserve) {
		set("reserve", reserve);
	}
	
	public String getReserve() {
		return getStr("reserve");
	}

	public void setLargeType(Integer largeType) {
		set("large_type", largeType);
	}
	
	public Integer getLargeType() {
		return getInt("large_type");
	}

	public void setBuyerMessage(String buyerMessage) {
		set("buyer_message", buyerMessage);
	}
	
	public String getBuyerMessage() {
		return getStr("buyer_message");
	}

	public void setCsRemark(String csRemark) {
		set("cs_remark", csRemark);
	}
	
	public String getCsRemark() {
		return getStr("cs_remark");
	}

	public void setRemarkFlag(Integer remarkFlag) {
		set("remark_flag", remarkFlag);
	}
	
	public Integer getRemarkFlag() {
		return getInt("remark_flag");
	}

	public void setPrintRemark(String printRemark) {
		set("print_remark", printRemark);
	}
	
	public String getPrintRemark() {
		return getStr("print_remark");
	}

	public void setGoodsTypeCount(Integer goodsTypeCount) {
		set("goods_type_count", goodsTypeCount);
	}
	
	public Integer getGoodsTypeCount() {
		return getInt("goods_type_count");
	}

	public void setGoodsCount(java.math.BigDecimal goodsCount) {
		set("goods_count", goodsCount);
	}
	
	public java.math.BigDecimal getGoodsCount() {
		return get("goods_count");
	}

	public void setGoodsAmount(java.math.BigDecimal goodsAmount) {
		set("goods_amount", goodsAmount);
	}
	
	public java.math.BigDecimal getGoodsAmount() {
		return get("goods_amount");
	}

	public void setPostAmount(java.math.BigDecimal postAmount) {
		set("post_amount", postAmount);
	}
	
	public java.math.BigDecimal getPostAmount() {
		return get("post_amount");
	}

	public void setOtherAmount(java.math.BigDecimal otherAmount) {
		set("other_amount", otherAmount);
	}
	
	public java.math.BigDecimal getOtherAmount() {
		return get("other_amount");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setReceivable(java.math.BigDecimal receivable) {
		set("receivable", receivable);
	}
	
	public java.math.BigDecimal getReceivable() {
		return get("receivable");
	}

	public void setDapAmount(java.math.BigDecimal dapAmount) {
		set("dap_amount", dapAmount);
	}
	
	public java.math.BigDecimal getDapAmount() {
		return get("dap_amount");
	}

	public void setCodAmount(java.math.BigDecimal codAmount) {
		set("cod_amount", codAmount);
	}
	
	public java.math.BigDecimal getCodAmount() {
		return get("cod_amount");
	}

	public void setExtCodFee(java.math.BigDecimal extCodFee) {
		set("ext_cod_fee", extCodFee);
	}
	
	public java.math.BigDecimal getExtCodFee() {
		return get("ext_cod_fee");
	}

	public void setGoodsCost(java.math.BigDecimal goodsCost) {
		set("goods_cost", goodsCost);
	}
	
	public java.math.BigDecimal getGoodsCost() {
		return get("goods_cost");
	}

	public void setPostCost(java.math.BigDecimal postCost) {
		set("post_cost", postCost);
	}
	
	public java.math.BigDecimal getPostCost() {
		return get("post_cost");
	}

	public void setPaid(java.math.BigDecimal paid) {
		set("paid", paid);
	}
	
	public java.math.BigDecimal getPaid() {
		return get("paid");
	}

	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}

	public void setProfit(java.math.BigDecimal profit) {
		set("profit", profit);
	}
	
	public java.math.BigDecimal getProfit() {
		return get("profit");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}
	
	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
	}
	
	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public void setCommission(java.math.BigDecimal commission) {
		set("commission", commission);
	}
	
	public java.math.BigDecimal getCommission() {
		return get("commission");
	}

	public void setInvoiceType(Integer invoiceType) {
		set("invoice_type", invoiceType);
	}
	
	public Integer getInvoiceType() {
		return getInt("invoice_type");
	}

	public void setInvoiceTitle(String invoiceTitle) {
		set("invoice_title", invoiceTitle);
	}
	
	public String getInvoiceTitle() {
		return getStr("invoice_title");
	}

	public void setInvoiceContent(String invoiceContent) {
		set("invoice_content", invoiceContent);
	}
	
	public String getInvoiceContent() {
		return getStr("invoice_content");
	}

	public void setSalesmanId(Integer salesmanId) {
		set("salesman_id", salesmanId);
	}
	
	public Integer getSalesmanId() {
		return getInt("salesman_id");
	}

	public void setCheckerId(Integer checkerId) {
		set("checker_id", checkerId);
	}
	
	public Integer getCheckerId() {
		return getInt("checker_id");
	}

	public void setFullname(String fullname) {
		set("fullname", fullname);
	}
	
	public String getFullname() {
		return getStr("fullname");
	}

	public void setCheckerName(String checkerName) {
		set("checker_name", checkerName);
	}
	
	public String getCheckerName() {
		return getStr("checker_name");
	}

	public void setFcheckerId(Integer fcheckerId) {
		set("fchecker_id", fcheckerId);
	}
	
	public Integer getFcheckerId() {
		return getInt("fchecker_id");
	}

	public void setCheckouterId(Integer checkouterId) {
		set("checkouter_id", checkouterId);
	}
	
	public Integer getCheckouterId() {
		return getInt("checkouter_id");
	}

	public void setStockoutNo(String stockoutNo) {
		set("stockout_no", stockoutNo);
	}
	
	public String getStockoutNo() {
		return getStr("stockout_no");
	}

	public void setFlagName(String flagName) {
		set("flag_name", flagName);
	}
	
	public String getFlagName() {
		return getStr("flag_name");
	}

	public void setTradeFrom(Integer tradeFrom) {
		set("trade_from", tradeFrom);
	}
	
	public Integer getTradeFrom() {
		return getInt("trade_from");
	}

	public void setSingleSpecNo(String singleSpecNo) {
		set("single_spec_no", singleSpecNo);
	}
	
	public String getSingleSpecNo() {
		return getStr("single_spec_no");
	}

	public void setRawGoodsCount(java.math.BigDecimal rawGoodsCount) {
		set("raw_goods_count", rawGoodsCount);
	}
	
	public java.math.BigDecimal getRawGoodsCount() {
		return get("raw_goods_count");
	}

	public void setRawGoodsTypeCount(Integer rawGoodsTypeCount) {
		set("raw_goods_type_count", rawGoodsTypeCount);
	}
	
	public Integer getRawGoodsTypeCount() {
		return getInt("raw_goods_type_count");
	}

	public void setCurrency(String currency) {
		set("currency", currency);
	}
	
	public String getCurrency() {
		return getStr("currency");
	}

	public void setSplitPackageNum(Integer splitPackageNum) {
		set("split_package_num", splitPackageNum);
	}
	
	public Integer getSplitPackageNum() {
		return getInt("split_package_num");
	}

	public void setInvoiceId(Integer invoiceId) {
		set("invoice_id", invoiceId);
	}
	
	public Integer getInvoiceId() {
		return getInt("invoice_id");
	}

	public void setVersionId(Integer versionId) {
		set("version_id", versionId);
	}
	
	public Integer getVersionId() {
		return getInt("version_id");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setIdCardType(Integer idCardType) {
		set("id_card_type", idCardType);
	}
	
	public Integer getIdCardType() {
		return getInt("id_card_type");
	}

	public void setIdCard(String idCard) {
		set("id_card", idCard);
	}
	
	public String getIdCard() {
		return getStr("id_card");
	}

}
