package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanHistory<M extends BaseHrGongdanHistory<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setTitle(String title) {
		set("title", title);
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public void setOrderNo(String orderNo) {
		set("orderNo", orderNo);
	}
	
	public String getOrderNo() {
		return getStr("orderNo");
	}

	public void setSubmitter(String submitter) {
		set("submitter", submitter);
	}
	
	public String getSubmitter() {
		return getStr("submitter");
	}

	public void setApplicationDate(String applicationDate) {
		set("applicationDate", applicationDate);
	}
	
	public String getApplicationDate() {
		return getStr("applicationDate");
	}

	public void setApprovalStatus(String approvalStatus) {
		set("approvalStatus", approvalStatus);
	}
	
	public String getApprovalStatus() {
		return getStr("approvalStatus");
	}

	public void setCompletionDate(String completionDate) {
		set("completionDate", completionDate);
	}
	
	public String getCompletionDate() {
		return getStr("completionDate");
	}

	public void setCurrentNode(String currentNode) {
		set("currentNode", currentNode);
	}
	
	public String getCurrentNode() {
		return getStr("currentNode");
	}

	public void setServiceClassify(String serviceClassify) {
		set("serviceClassify", serviceClassify);
	}
	
	public String getServiceClassify() {
		return getStr("serviceClassify");
	}

	public void setCurrentApprover(String currentApprover) {
		set("currentApprover", currentApprover);
	}
	
	public String getCurrentApprover() {
		return getStr("currentApprover");
	}

	public void setShopName(String shopName) {
		set("shopName", shopName);
	}
	
	public String getShopName() {
		return getStr("shopName");
	}

	public void setSendContent(String sendContent) {
		set("sendContent", sendContent);
	}
	
	public String getSendContent() {
		return getStr("sendContent");
	}

	public void setInstallPrice(String installPrice) {
		set("installPrice", installPrice);
	}
	
	public String getInstallPrice() {
		return getStr("installPrice");
	}

	public void setModificationPaid(String modificationPaid) {
		set("modificationPaid", modificationPaid);
	}
	
	public String getModificationPaid() {
		return getStr("modificationPaid");
	}

	public void setInstallMaster(String installMaster) {
		set("installMaster", installMaster);
	}
	
	public String getInstallMaster() {
		return getStr("installMaster");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}
	
	public Integer getQuantity() {
		return getInt("quantity");
	}

	public void setReserveInstallDate(String reserveInstallDate) {
		set("reserveInstallDate", reserveInstallDate);
	}
	
	public String getReserveInstallDate() {
		return getStr("reserveInstallDate");
	}

	public void setAppointResult(String appointResult) {
		set("appointResult", appointResult);
	}
	
	public String getAppointResult() {
		return getStr("appointResult");
	}

	public void setFuselageCode(String fuselageCode) {
		set("fuselageCode", fuselageCode);
	}
	
	public String getFuselageCode() {
		return getStr("fuselageCode");
	}

	public void setInstallFeeSettle(String installFeeSettle) {
		set("installFeeSettle", installFeeSettle);
	}
	
	public String getInstallFeeSettle() {
		return getStr("installFeeSettle");
	}

	public void setJobNum(String jobNum) {
		set("jobNum", jobNum);
	}
	
	public String getJobNum() {
		return getStr("jobNum");
	}

	public void setDepartment(String department) {
		set("department", department);
	}
	
	public String getDepartment() {
		return getStr("department");
	}

	public void setCourierNum(String courierNum) {
		set("courierNum", courierNum);
	}
	
	public String getCourierNum() {
		return getStr("courierNum");
	}

	public void setProductInfo(String productInfo) {
		set("productInfo", productInfo);
	}
	
	public String getProductInfo() {
		return getStr("productInfo");
	}

	public void setCustomerShort(String customerShort) {
		set("customerShort", customerShort);
	}
	
	public String getCustomerShort() {
		return getStr("customerShort");
	}

	public void setOrderType(String orderType) {
		set("orderType", orderType);
	}
	
	public String getOrderType() {
		return getStr("orderType");
	}

	public void setDepartFullName(String departFullName) {
		set("departFullName", departFullName);
	}
	
	public String getDepartFullName() {
		return getStr("departFullName");
	}

}
