package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanYzjOvertime<M extends BaseHrGongdanYzjOvertime<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setDeptName(String deptName) {
		set("deptName", deptName);
	}
	
	public String getDeptName() {
		return getStr("deptName");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}
	
	public String getCreator() {
		return getStr("creator");
	}

	public void setFormDefId(String formDefId) {
		set("formDefId", formDefId);
	}
	
	public String getFormDefId() {
		return getStr("formDefId");
	}

	public void setTitle(String title) {
		set("title", title);
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public void setSerialNo(String serialNo) {
		set("serialNo", serialNo);
	}
	
	public String getSerialNo() {
		return getStr("serialNo");
	}

	public void setFormCodeId(String formCodeId) {
		set("formCodeId", formCodeId);
	}
	
	public String getFormCodeId() {
		return getStr("formCodeId");
	}

	public void setFlowInstId(String flowInstId) {
		set("flowInstId", flowInstId);
	}
	
	public String getFlowInstId() {
		return getStr("flowInstId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreateName(String createName) {
		set("createName", createName);
	}
	
	public String getCreateName() {
		return getStr("createName");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setFormInstId(String formInstId) {
		set("formInstId", formInstId);
	}
	
	public String getFormInstId() {
		return getStr("formInstId");
	}

}
