package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanZmnLog<M extends BaseHrGongdanZmnLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setFuncId(String funcId) {
		set("funcId", funcId);
	}
	
	public String getFuncId() {
		return getStr("funcId");
	}

	public void setOptTime(Long optTime) {
		set("optTime", optTime);
	}
	
	public Long getOptTime() {
		return getLong("optTime");
	}

	public void setOrderId(String orderId) {
		set("orderId", orderId);
	}
	
	public String getOrderId() {
		return getStr("orderId");
	}

	public void setThirdOrderId(String thirdOrderId) {
		set("thirdOrderId", thirdOrderId);
	}
	
	public String getThirdOrderId() {
		return getStr("thirdOrderId");
	}

	public void setMasterName(String masterName) {
		set("masterName", masterName);
	}
	
	public String getMasterName() {
		return getStr("masterName");
	}

	public void setMasterPhone(String masterPhone) {
		set("masterPhone", masterPhone);
	}
	
	public String getMasterPhone() {
		return getStr("masterPhone");
	}

	public void setDutyTime(Long dutyTime) {
		set("dutyTime", dutyTime);
	}
	
	public Long getDutyTime() {
		return getLong("dutyTime");
	}

	public void setCompleteRemark(String completeRemark) {
		set("completeRemark", completeRemark);
	}
	
	public String getCompleteRemark() {
		return getStr("completeRemark");
	}

	public void setCompleteUrl(String completeUrl) {
		set("completeUrl", completeUrl);
	}
	
	public String getCompleteUrl() {
		return getStr("completeUrl");
	}

	public void setCancelRemark(String cancelRemark) {
		set("cancelRemark", cancelRemark);
	}
	
	public String getCancelRemark() {
		return getStr("cancelRemark");
	}

	public void setFactoryRemark(String factoryRemark) {
		set("factoryRemark", factoryRemark);
	}
	
	public String getFactoryRemark() {
		return getStr("factoryRemark");
	}

}
