package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdan<M extends BaseHrGongdan<M>> extends Model<M> implements IBean {

	public void setTitle(String Title) {
		set("Title", Title);
	}
	
	public String getTitle() {
		return getStr("Title");
	}

	public void setOID(Integer OID) {
		set("OID", OID);
	}
	
	public Integer getOID() {
		return getInt("OID");
	}

	public void setFID(Integer FID) {
		set("FID", FID);
	}
	
	public Integer getFID() {
		return getInt("FID");
	}

	public void setRDT(String RDT) {
		set("RDT", RDT);
	}
	
	public String getRDT() {
		return getStr("RDT");
	}

	public void setCDT(String CDT) {
		set("CDT", CDT);
	}
	
	public String getCDT() {
		return getStr("CDT");
	}

	public void setRec(String Rec) {
		set("Rec", Rec);
	}
	
	public String getRec() {
		return getStr("Rec");
	}

	public void setEmps(String Emps) {
		set("Emps", Emps);
	}
	
	public String getEmps() {
		return getStr("Emps");
	}

	public void setFkDept(String fkDept) {
		set("FK_Dept", fkDept);
	}
	
	public String getFkDept() {
		return getStr("FK_Dept");
	}

	public void setFkNy(String fkNy) {
		set("FK_NY", fkNy);
	}
	
	public String getFkNy() {
		return getStr("FK_NY");
	}

	public void setMyNum(Integer MyNum) {
		set("MyNum", MyNum);
	}
	
	public Integer getMyNum() {
		return getInt("MyNum");
	}

	public void setPNodeID(Integer PNodeID) {
		set("PNodeID", PNodeID);
	}
	
	public Integer getPNodeID() {
		return getInt("PNodeID");
	}

	public void setGUID(String GUID) {
		set("GUID", GUID);
	}
	
	public String getGUID() {
		return getStr("GUID");
	}

	public void setPEmp(String PEmp) {
		set("PEmp", PEmp);
	}
	
	public String getPEmp() {
		return getStr("PEmp");
	}

	public void setPrjNo(String PrjNo) {
		set("PrjNo", PrjNo);
	}
	
	public String getPrjNo() {
		return getStr("PrjNo");
	}

	public void setAtPara(String AtPara) {
		set("AtPara", AtPara);
	}
	
	public String getAtPara() {
		return getStr("AtPara");
	}

	public void setBillNo(String BillNo) {
		set("BillNo", BillNo);
	}
	
	public String getBillNo() {
		return getStr("BillNo");
	}

	public void setPrjName(String PrjName) {
		set("PrjName", PrjName);
	}
	
	public String getPrjName() {
		return getStr("PrjName");
	}

	public void setFlowNote(String FlowNote) {
		set("FlowNote", FlowNote);
	}
	
	public String getFlowNote() {
		return getStr("FlowNote");
	}

	public void setWFSta(Integer WFSta) {
		set("WFSta", WFSta);
	}
	
	public Integer getWFSta() {
		return getInt("WFSta");
	}

	public void setPWorkID(Integer PWorkID) {
		set("PWorkID", PWorkID);
	}
	
	public Integer getPWorkID() {
		return getInt("PWorkID");
	}

	public void setFlowDaySpan(java.math.BigDecimal FlowDaySpan) {
		set("FlowDaySpan", FlowDaySpan);
	}
	
	public java.math.BigDecimal getFlowDaySpan() {
		return get("FlowDaySpan");
	}

	public void setFlowEndNode(Integer FlowEndNode) {
		set("FlowEndNode", FlowEndNode);
	}
	
	public Integer getFlowEndNode() {
		return getInt("FlowEndNode");
	}

	public void setFlowEnderRDT(String FlowEnderRDT) {
		set("FlowEnderRDT", FlowEnderRDT);
	}
	
	public String getFlowEnderRDT() {
		return getStr("FlowEnderRDT");
	}

	public void setFlowStartRDT(String FlowStartRDT) {
		set("FlowStartRDT", FlowStartRDT);
	}
	
	public String getFlowStartRDT() {
		return getStr("FlowStartRDT");
	}

	public void setPFlowNo(String PFlowNo) {
		set("PFlowNo", PFlowNo);
	}
	
	public String getPFlowNo() {
		return getStr("PFlowNo");
	}

	public void setFlowEmps(String FlowEmps) {
		set("FlowEmps", FlowEmps);
	}
	
	public String getFlowEmps() {
		return getStr("FlowEmps");
	}

	public void setWFState(Integer WFState) {
		set("WFState", WFState);
	}
	
	public Integer getWFState() {
		return getInt("WFState");
	}

	public void setFlowEnder(String FlowEnder) {
		set("FlowEnder", FlowEnder);
	}
	
	public String getFlowEnder() {
		return getStr("FlowEnder");
	}

	public void setFlowStarter(String FlowStarter) {
		set("FlowStarter", FlowStarter);
	}
	
	public String getFlowStarter() {
		return getStr("FlowStarter");
	}

	public void setServiceNo(String serviceNo) {
		set("serviceNo", serviceNo);
	}
	
	public String getServiceNo() {
		return getStr("serviceNo");
	}

	public void setServiceSystem(String serviceSystem) {
		set("serviceSystem", serviceSystem);
	}
	
	public String getServiceSystem() {
		return getStr("serviceSystem");
	}

	public void setServiceType(String serviceType) {
		set("serviceType", serviceType);
	}
	
	public String getServiceType() {
		return getStr("serviceType");
	}

	public void setServiceZt(String serviceZt) {
		set("serviceZt", serviceZt);
	}
	
	public String getServiceZt() {
		return getStr("serviceZt");
	}

	public void setReworkId(String reworkId) {
		set("reworkId", reworkId);
	}
	
	public String getReworkId() {
		return getStr("reworkId");
	}

	public void setFactory(Integer factory) {
		set("factory", factory);
	}
	
	public Integer getFactory() {
		return getInt("factory");
	}

	public void setFacInWarranty(Integer facInWarranty) {
		set("facInWarranty", facInWarranty);
	}
	
	public Integer getFacInWarranty() {
		return getInt("facInWarranty");
	}

	public void setSmcCityId(Integer smcCityId) {
		set("smcCityId", smcCityId);
	}
	
	public Integer getSmcCityId() {
		return getInt("smcCityId");
	}

	public void setSmcProvinceId(Integer smcProvinceId) {
		set("smcProvinceId", smcProvinceId);
	}
	
	public Integer getSmcProvinceId() {
		return getInt("smcProvinceId");
	}

	public void setSmcDistrictId(Integer smcDistrictId) {
		set("smcDistrictId", smcDistrictId);
	}
	
	public Integer getSmcDistrictId() {
		return getInt("smcDistrictId");
	}

	public void setTelephone(String telephone) {
		set("telephone", telephone);
	}
	
	public String getTelephone() {
		return getStr("telephone");
	}

	public void setContactName(String contactName) {
		set("contactName", contactName);
	}
	
	public String getContactName() {
		return getStr("contactName");
	}

	public void setGender(String gender) {
		set("gender", gender);
	}
	
	public String getGender() {
		return getStr("gender");
	}

	public void setAddress(String address) {
		set("address", address);
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public void setDutyTime(java.util.Date dutyTime) {
		set("dutyTime", dutyTime);
	}
	
	public java.util.Date getDutyTime() {
		return get("dutyTime");
	}

	public void setProductId(Integer productId) {
		set("productId", productId);
	}
	
	public Integer getProductId() {
		return getInt("productId");
	}

	public void setFacProductId(String facProductId) {
		set("facProductId", facProductId);
	}
	
	public String getFacProductId() {
		return getStr("facProductId");
	}

	public void setProductCount(Integer productCount) {
		set("productCount", productCount);
	}
	
	public Integer getProductCount() {
		return getInt("productCount");
	}

	public void setOrderDiscountAmount(Integer orderDiscountAmount) {
		set("orderDiscountAmount", orderDiscountAmount);
	}
	
	public Integer getOrderDiscountAmount() {
		return getInt("orderDiscountAmount");
	}

	public void setOrderDiscountSourceData(String orderDiscountSourceData) {
		set("orderDiscountSourceData", orderDiscountSourceData);
	}
	
	public String getOrderDiscountSourceData() {
		return getStr("orderDiscountSourceData");
	}

	public void setOrderDiscountRemark(String orderDiscountRemark) {
		set("orderDiscountRemark", orderDiscountRemark);
	}
	
	public String getOrderDiscountRemark() {
		return getStr("orderDiscountRemark");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public void setSMC(String SMC) {
		set("SMC", SMC);
	}
	
	public String getSMC() {
		return getStr("SMC");
	}

	public void setOrderDiscount(Double orderDiscount) {
		set("orderDiscount", orderDiscount);
	}
	
	public Double getOrderDiscount() {
		return getDouble("orderDiscount");
	}

	public void setServiceSegmentation(String serviceSegmentation) {
		set("serviceSegmentation", serviceSegmentation);
	}
	
	public String getServiceSegmentation() {
		return getStr("serviceSegmentation");
	}

	public void setOrderId(String orderId) {
		set("orderId", orderId);
	}
	
	public String getOrderId() {
		return getStr("orderId");
	}

	public void setMasterName(String masterName) {
		set("masterName", masterName);
	}
	
	public String getMasterName() {
		return getStr("masterName");
	}

	public void setMasterPhone(String masterPhone) {
		set("masterPhone", masterPhone);
	}
	
	public String getMasterPhone() {
		return getStr("masterPhone");
	}

	public void setProductPictureUrls(String productPictureUrls) {
		set("productPictureUrls", productPictureUrls);
	}
	
	public String getProductPictureUrls() {
		return getStr("productPictureUrls");
	}

	public void setServiceSp(String serviceSp) {
		set("serviceSp", serviceSp);
	}
	
	public String getServiceSp() {
		return getStr("serviceSp");
	}

}
