package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanAreaRelation<M extends BaseHrGongdanAreaRelation<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setProvince(String province) {
		set("province", province);
	}
	
	public String getProvince() {
		return getStr("province");
	}

	public void setCity(String city) {
		set("city", city);
	}
	
	public String getCity() {
		return getStr("city");
	}

	public void setDistrict(String district) {
		set("district", district);
	}
	
	public String getDistrict() {
		return getStr("district");
	}

	public void setFkSystem(String fkSystem) {
		set("fk_system", fkSystem);
	}
	
	public String getFkSystem() {
		return getStr("fk_system");
	}

	public void setFkEmp(String fkEmp) {
		set("fk_emp", fkEmp);
	}
	
	public String getFkEmp() {
		return getStr("fk_emp");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setAreaType(String areaType) {
		set("area_type", areaType);
	}
	
	public String getAreaType() {
		return getStr("area_type");
	}

	public void setPriority(String priority) {
		set("priority", priority);
	}
	
	public String getPriority() {
		return getStr("priority");
	}

}
