package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanFjf<M extends BaseHrGongdanFjf<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setOrderNumber(String orderNumber) {
		set("orderNumber", orderNumber);
	}
	
	public String getOrderNumber() {
		return getStr("orderNumber");
	}

	public void setWorkId(Integer workId) {
		set("workId", workId);
	}
	
	public Integer getWorkId() {
		return getInt("workId");
	}

	public void setServiceNo(String serviceNo) {
		set("serviceNo", serviceNo);
	}
	
	public String getServiceNo() {
		return getStr("serviceNo");
	}

	public void setFjf(Double fjf) {
		set("fjf", fjf);
	}
	
	public Double getFjf() {
		return getDouble("fjf");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public void setSp(Integer sp) {
		set("sp", sp);
	}
	
	public Integer getSp() {
		return getInt("sp");
	}

	public void setSpRemark(String spRemark) {
		set("spRemark", spRemark);
	}
	
	public String getSpRemark() {
		return getStr("spRemark");
	}

	public void setSpTime(java.util.Date spTime) {
		set("spTime", spTime);
	}
	
	public java.util.Date getSpTime() {
		return get("spTime");
	}

	public void setSptor(String sptor) {
		set("sptor", sptor);
	}
	
	public String getSptor() {
		return getStr("sptor");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreatetor(String createtor) {
		set("createtor", createtor);
	}
	
	public String getCreatetor() {
		return getStr("createtor");
	}

}
