package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanWdtTradeGoods<M extends BaseHrGongdanWdtTradeGoods<M>> extends Model<M> implements IBean {

	public void setRecId(Integer recId) {
		set("rec_id", recId);
	}
	
	public Integer getRecId() {
		return getInt("rec_id");
	}

	public void setTradeId(Integer tradeId) {
		set("trade_id", tradeId);
	}
	
	public Integer getTradeId() {
		return getInt("trade_id");
	}

	public void setSpecId(Integer specId) {
		set("spec_id", specId);
	}
	
	public Integer getSpecId() {
		return getInt("spec_id");
	}

	public void setPlatformId(Integer platformId) {
		set("platform_id", platformId);
	}
	
	public Integer getPlatformId() {
		return getInt("platform_id");
	}

	public void setSrcOid(String srcOid) {
		set("src_oid", srcOid);
	}
	
	public String getSrcOid() {
		return getStr("src_oid");
	}

	public void setPlatformGoodsId(String platformGoodsId) {
		set("platform_goods_id", platformGoodsId);
	}
	
	public String getPlatformGoodsId() {
		return getStr("platform_goods_id");
	}

	public void setPlatformSpecId(String platformSpecId) {
		set("platform_spec_id", platformSpecId);
	}
	
	public String getPlatformSpecId() {
		return getStr("platform_spec_id");
	}

	public void setSuiteId(Integer suiteId) {
		set("suite_id", suiteId);
	}
	
	public Integer getSuiteId() {
		return getInt("suite_id");
	}

	public void setFlag(Integer flag) {
		set("flag", flag);
	}
	
	public Integer getFlag() {
		return getInt("flag");
	}

	public void setSrcTid(String srcTid) {
		set("src_tid", srcTid);
	}
	
	public String getSrcTid() {
		return getStr("src_tid");
	}

	public void setGiftType(Integer giftType) {
		set("gift_type", giftType);
	}
	
	public Integer getGiftType() {
		return getInt("gift_type");
	}

	public void setRefundStatus(Integer refundStatus) {
		set("refund_status", refundStatus);
	}
	
	public Integer getRefundStatus() {
		return getInt("refund_status");
	}

	public void setGuaranteeMode(Integer guaranteeMode) {
		set("guarantee_mode", guaranteeMode);
	}
	
	public Integer getGuaranteeMode() {
		return getInt("guarantee_mode");
	}

	public void setDeliveryTerm(Integer deliveryTerm) {
		set("delivery_term", deliveryTerm);
	}
	
	public Integer getDeliveryTerm() {
		return getInt("delivery_term");
	}

	public void setBindOid(String bindOid) {
		set("bind_oid", bindOid);
	}
	
	public String getBindOid() {
		return getStr("bind_oid");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setActualNum(java.math.BigDecimal actualNum) {
		set("actual_num", actualNum);
	}
	
	public java.math.BigDecimal getActualNum() {
		return get("actual_num");
	}

	public void setRefundNum(java.math.BigDecimal refundNum) {
		set("refund_num", refundNum);
	}
	
	public java.math.BigDecimal getRefundNum() {
		return get("refund_num");
	}

	public void setOrderPrice(java.math.BigDecimal orderPrice) {
		set("order_price", orderPrice);
	}
	
	public java.math.BigDecimal getOrderPrice() {
		return get("order_price");
	}

	public void setSharePrice(java.math.BigDecimal sharePrice) {
		set("share_price", sharePrice);
	}
	
	public java.math.BigDecimal getSharePrice() {
		return get("share_price");
	}

	public void setAdjust(java.math.BigDecimal adjust) {
		set("adjust", adjust);
	}
	
	public java.math.BigDecimal getAdjust() {
		return get("adjust");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setShareAmount(java.math.BigDecimal shareAmount) {
		set("share_amount", shareAmount);
	}
	
	public java.math.BigDecimal getShareAmount() {
		return get("share_amount");
	}

	public void setSharePost(java.math.BigDecimal sharePost) {
		set("share_post", sharePost);
	}
	
	public java.math.BigDecimal getSharePost() {
		return get("share_post");
	}

	public void setPaid(java.math.BigDecimal paid) {
		set("paid", paid);
	}
	
	public java.math.BigDecimal getPaid() {
		return get("paid");
	}

	public void setGoodsName(String goodsName) {
		set("goods_name", goodsName);
	}
	
	public String getGoodsName() {
		return getStr("goods_name");
	}

	public void setProp2(String prop2) {
		set("prop2", prop2);
	}
	
	public String getProp2() {
		return getStr("prop2");
	}

	public void setBarcode(String barcode) {
		set("barcode", barcode);
	}
	
	public String getBarcode() {
		return getStr("barcode");
	}

	public void setGoodsId(Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	public Integer getGoodsId() {
		return getInt("goods_id");
	}

	public void setGoodsNo(String goodsNo) {
		set("goods_no", goodsNo);
	}
	
	public String getGoodsNo() {
		return getStr("goods_no");
	}

	public void setSpecName(String specName) {
		set("spec_name", specName);
	}
	
	public String getSpecName() {
		return getStr("spec_name");
	}

	public void setSpecNo(String specNo) {
		set("spec_no", specNo);
	}
	
	public String getSpecNo() {
		return getStr("spec_no");
	}

	public void setSpecCode(String specCode) {
		set("spec_code", specCode);
	}
	
	public String getSpecCode() {
		return getStr("spec_code");
	}

	public void setSuiteNo(String suiteNo) {
		set("suite_no", suiteNo);
	}
	
	public String getSuiteNo() {
		return getStr("suite_no");
	}

	public void setSuiteName(String suiteName) {
		set("suite_name", suiteName);
	}
	
	public String getSuiteName() {
		return getStr("suite_name");
	}

	public void setSuiteNum(java.math.BigDecimal suiteNum) {
		set("suite_num", suiteNum);
	}
	
	public java.math.BigDecimal getSuiteNum() {
		return get("suite_num");
	}

	public void setSuiteAmount(java.math.BigDecimal suiteAmount) {
		set("suite_amount", suiteAmount);
	}
	
	public java.math.BigDecimal getSuiteAmount() {
		return get("suite_amount");
	}

	public void setSuiteDiscount(java.math.BigDecimal suiteDiscount) {
		set("suite_discount", suiteDiscount);
	}
	
	public java.math.BigDecimal getSuiteDiscount() {
		return get("suite_discount");
	}

	public void setShareAmount2(java.math.BigDecimal shareAmount2) {
		set("share_amount2", shareAmount2);
	}
	
	public java.math.BigDecimal getShareAmount2() {
		return get("share_amount2");
	}

	public void setIsPrintSuite(Integer isPrintSuite) {
		set("is_print_suite", isPrintSuite);
	}
	
	public Integer getIsPrintSuite() {
		return getInt("is_print_suite");
	}

	public void setIsZeroCost(Integer isZeroCost) {
		set("is_zero_cost", isZeroCost);
	}
	
	public Integer getIsZeroCost() {
		return getInt("is_zero_cost");
	}

	public void setStockReserved(Integer stockReserved) {
		set("stock_reserved", stockReserved);
	}
	
	public Integer getStockReserved() {
		return getInt("stock_reserved");
	}

	public void setIsConsigned(Integer isConsigned) {
		set("is_consigned", isConsigned);
	}
	
	public Integer getIsConsigned() {
		return getInt("is_consigned");
	}

	public void setIsReceived(Integer isReceived) {
		set("is_received", isReceived);
	}
	
	public Integer getIsReceived() {
		return getInt("is_received");
	}

	public void setIsMaster(Integer isMaster) {
		set("is_master", isMaster);
	}
	
	public Integer getIsMaster() {
		return getInt("is_master");
	}

	public void setApiGoodsName(String apiGoodsName) {
		set("api_goods_name", apiGoodsName);
	}
	
	public String getApiGoodsName() {
		return getStr("api_goods_name");
	}

	public void setApiSpecName(String apiSpecName) {
		set("api_spec_name", apiSpecName);
	}
	
	public String getApiSpecName() {
		return getStr("api_spec_name");
	}

	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}

	public void setCommission(java.math.BigDecimal commission) {
		set("commission", commission);
	}
	
	public java.math.BigDecimal getCommission() {
		return get("commission");
	}

	public void setGoodsType(Integer goodsType) {
		set("goods_type", goodsType);
	}
	
	public Integer getGoodsType() {
		return getInt("goods_type");
	}

	public void setLargeType(Integer largeType) {
		set("large_type", largeType);
	}
	
	public Integer getLargeType() {
		return getInt("large_type");
	}

	public void setInvoiceType(Integer invoiceType) {
		set("invoice_type", invoiceType);
	}
	
	public Integer getInvoiceType() {
		return getInt("invoice_type");
	}

	public void setInvoiceContent(String invoiceContent) {
		set("invoice_content", invoiceContent);
	}
	
	public String getInvoiceContent() {
		return getStr("invoice_content");
	}

	public void setFromMask(Integer fromMask) {
		set("from_mask", fromMask);
	}
	
	public Integer getFromMask() {
		return getInt("from_mask");
	}

	public void setCid(Integer cid) {
		set("cid", cid);
	}
	
	public Integer getCid() {
		return getInt("cid");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
	}
	
	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public void setBaseUnitId(Integer baseUnitId) {
		set("base_unit_id", baseUnitId);
	}
	
	public Integer getBaseUnitId() {
		return getInt("base_unit_id");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setPayId(String payId) {
		set("pay_id", payId);
	}
	
	public String getPayId() {
		return getStr("pay_id");
	}

	public void setPayStatus(Integer payStatus) {
		set("pay_status", payStatus);
	}
	
	public Integer getPayStatus() {
		return getInt("pay_status");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}
	
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

}
