package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanBook<M extends BaseHrGongdanBook<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setOrderNumber(String orderNumber) {
		set("orderNumber", orderNumber);
	}
	
	public String getOrderNumber() {
		return getStr("orderNumber");
	}

	public void setOrderNo(String orderNo) {
		set("orderNo", orderNo);
	}
	
	public String getOrderNo() {
		return getStr("orderNo");
	}

	public void setCustomerNo(String customerNo) {
		set("customerNo", customerNo);
	}
	
	public String getCustomerNo() {
		return getStr("customerNo");
	}

	public void setContact(String contact) {
		set("contact", contact);
	}
	
	public String getContact() {
		return getStr("contact");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public void setBookDate(String bookDate) {
		set("bookDate", bookDate);
	}
	
	public String getBookDate() {
		return getStr("bookDate");
	}

	public void setProvince(String province) {
		set("province", province);
	}
	
	public String getProvince() {
		return getStr("province");
	}

	public void setCity(String city) {
		set("city", city);
	}
	
	public String getCity() {
		return getStr("city");
	}

	public void setDistrict(String district) {
		set("district", district);
	}
	
	public String getDistrict() {
		return getStr("district");
	}

	public void setSmc(String smc) {
		set("smc", smc);
	}
	
	public String getSmc() {
		return getStr("smc");
	}

	public void setAddress(String address) {
		set("address", address);
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public void setBuyStore(String buyStore) {
		set("buyStore", buyStore);
	}
	
	public String getBuyStore() {
		return getStr("buyStore");
	}

	public void setBuyType(String buyType) {
		set("buyType", buyType);
	}
	
	public String getBuyType() {
		return getStr("buyType");
	}

	public void setBuyNum(Integer buyNum) {
		set("buyNum", buyNum);
	}
	
	public Integer getBuyNum() {
		return getInt("buyNum");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public void setIsGenerate(Integer isGenerate) {
		set("is_generate", isGenerate);
	}
	
	public Integer getIsGenerate() {
		return getInt("is_generate");
	}

	public void setStandardFee(java.math.BigDecimal standardFee) {
		set("standardFee", standardFee);
	}
	
	public java.math.BigDecimal getStandardFee() {
		return get("standardFee");
	}

	public void setAdjustmentFee(java.math.BigDecimal adjustmentFee) {
		set("adjustmentFee", adjustmentFee);
	}
	
	public java.math.BigDecimal getAdjustmentFee() {
		return get("adjustmentFee");
	}

	public void setTotalFee(java.math.BigDecimal totalFee) {
		set("totalFee", totalFee);
	}
	
	public java.math.BigDecimal getTotalFee() {
		return get("totalFee");
	}

	public void setPayType(Integer payType) {
		set("payType", payType);
	}
	
	public Integer getPayType() {
		return getInt("payType");
	}

	public void setSourceType(Integer sourceType) {
		set("sourceType", sourceType);
	}
	
	public Integer getSourceType() {
		return getInt("sourceType");
	}

	public void setDeal(String deal) {
		set("deal", deal);
	}
	
	public String getDeal() {
		return getStr("deal");
	}

	public void setPhoto(String photo) {
		set("photo", photo);
	}
	
	public String getPhoto() {
		return getStr("photo");
	}

	public void setOpenId(String openId) {
		set("open_id", openId);
	}
	
	public String getOpenId() {
		return getStr("open_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}
	
	public String getCreator() {
		return getStr("creator");
	}

	public void setCreatorPhone(String creatorPhone) {
		set("creatorPhone", creatorPhone);
	}
	
	public String getCreatorPhone() {
		return getStr("creatorPhone");
	}

	public void setZt(String zt) {
		set("zt", zt);
	}
	
	public String getZt() {
		return getStr("zt");
	}

	public void setGoodsType(Integer goodsType) {
		set("goodsType", goodsType);
	}
	
	public Integer getGoodsType() {
		return getInt("goodsType");
	}

}
