package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanFjf<M extends BaseHrGongdanFjf<M>> extends Model<M> implements IBean {

	public void setOID(Long OID) {
		set("OID", OID);
	}
	
	public Long getOID() {
		return getLong("OID");
	}

	public void setFjf(Integer fjf) {
		set("fjf", fjf);
	}
	
	public Integer getFjf() {
		return getInt("fjf");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public void setSp(Integer sp) {
		set("sp", sp);
	}
	
	public Integer getSp() {
		return getInt("sp");
	}

	public void setSpRemark(String spRemark) {
		set("spRemark", spRemark);
	}
	
	public String getSpRemark() {
		return getStr("spRemark");
	}

}
