package com.kakarote.crm9.erp.yeyx.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrGongdanSabLog<M extends BaseHrGongdanSabLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setFuncId(String funcId) {
		set("funcId", funcId);
	}
	
	public String getFuncId() {
		return getStr("funcId");
	}

	public void setOptTime(Long optTime) {
		set("optTime", optTime);
	}
	
	public Long getOptTime() {
		return getLong("optTime");
	}

	public void setOrderId(String orderId) {
		set("orderId", orderId);
	}
	
	public String getOrderId() {
		return getStr("orderId");
	}

	public void setThirdOrderId(String thirdOrderId) {
		set("thirdOrderId", thirdOrderId);
	}
	
	public String getThirdOrderId() {
		return getStr("thirdOrderId");
	}

	public void setMasterName(String masterName) {
		set("masterName", masterName);
	}
	
	public String getMasterName() {
		return getStr("masterName");
	}

	public void setMasterPhone(String masterPhone) {
		set("masterPhone", masterPhone);
	}
	
	public String getMasterPhone() {
		return getStr("masterPhone");
	}

	public void setDutyTime(String dutyTime) {
		set("dutyTime", dutyTime);
	}
	
	public String getDutyTime() {
		return getStr("dutyTime");
	}

	public void setCompleteTime(String completeTime) {
		set("completeTime", completeTime);
	}
	
	public String getCompleteTime() {
		return getStr("completeTime");
	}

	public void setCompleteRemark(String completeRemark) {
		set("completeRemark", completeRemark);
	}
	
	public String getCompleteRemark() {
		return getStr("completeRemark");
	}

	public void setCompleteUrl(String completeUrl) {
		set("completeUrl", completeUrl);
	}
	
	public String getCompleteUrl() {
		return getStr("completeUrl");
	}

	public void setCancelRemark(String cancelRemark) {
		set("cancelRemark", cancelRemark);
	}
	
	public String getCancelRemark() {
		return getStr("cancelRemark");
	}

}
