
package com.landray.kmss.km.review.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-12-01T18:13:43.511+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class IKmReviewWebserviceService_IKmReviewWebserviceServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewWebserviceServiceService");

    private IKmReviewWebserviceService_IKmReviewWebserviceServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IKmReviewWebserviceServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IKmReviewWebserviceServiceService ss = new IKmReviewWebserviceServiceService(wsdlURL, SERVICE_NAME);
        IKmReviewWebserviceService port = ss.getIKmReviewWebserviceServicePort();  
        
        {
        System.out.println("Invoking approveProcess...");
        KmReviewParamterForm _approveProcess_arg0 = new KmReviewParamterForm();
        try {
            String _approveProcess__return = port.approveProcess(_approveProcess_arg0);
            System.out.println("approveProcess.result=" + _approveProcess__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateReviewInfo...");
        KmReviewParamterForm _updateReviewInfo_arg0 = new KmReviewParamterForm();
        try {
            String _updateReviewInfo__return = port.updateReviewInfo(_updateReviewInfo_arg0);
            System.out.println("updateReviewInfo.result=" + _updateReviewInfo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addReview...");
        KmReviewParamterForm _addReview_arg0 = new KmReviewParamterForm();
        try {
            String _addReview__return = port.addReview(_addReview_arg0);
            System.out.println("addReview.result=" + _addReview__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
