package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityPlaybill<M extends BasePortActivityPlaybill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPbQrcode(byte[] pbQrcode) {
		set("pb_qrcode", pbQrcode);
	}

	public byte[] getPbQrcode() {
		return get("pb_qrcode");
	}

	public void setPbSourceOpenid(java.lang.String pbSourceOpenid) {
		set("pb_source_openid", pbSourceOpenid);
	}

	public java.lang.String getPbSourceOpenid() {
		return getStr("pb_source_openid");
	}

	public void setPbLeadingOpenid(java.lang.String pbLeadingOpenid) {
		set("pb_leading_openid", pbLeadingOpenid);
	}

	public java.lang.String getPbLeadingOpenid() {
		return getStr("pb_leading_openid");
	}

	public void setPbAcId(java.lang.Integer pbAcId) {
		set("pb_ac_id", pbAcId);
	}

	public java.lang.Integer getPbAcId() {
		return getInt("pb_ac_id");
	}

	public void setPbPlaybill(java.lang.String pbPlaybill) {
		set("pb_playbill", pbPlaybill);
	}

	public java.lang.String getPbPlaybill() {
		return getStr("pb_playbill");
	}

}
