package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityShare<M extends BasePortActivityShare<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setSrPbId(Integer srPbId) {
		set("sr_pb_id", srPbId);
	}
	
	public Integer getSrPbId() {
		return getInt("sr_pb_id");
	}

	public void setSrAsId(Integer srAsId) {
		set("sr_as_id", srAsId);
	}
	
	public Integer getSrAsId() {
		return getInt("sr_as_id");
	}

	public void setSrShareOpenid(String srShareOpenid) {
		set("sr_share_openid", srShareOpenid);
	}
	
	public String getSrShareOpenid() {
		return getStr("sr_share_openid");
	}

	public void setSrShareInfo(String srShareInfo) {
		set("sr_share_info", srShareInfo);
	}
	
	public String getSrShareInfo() {
		return getStr("sr_share_info");
	}

	public void setSrToShareOpenid(String srToShareOpenid) {
		set("sr_to_share_openid", srToShareOpenid);
	}
	
	public String getSrToShareOpenid() {
		return getStr("sr_to_share_openid");
	}

	public void setSrToShareInfo(String srToShareInfo) {
		set("sr_to_share_info", srToShareInfo);
	}
	
	public String getSrToShareInfo() {
		return getStr("sr_to_share_info");
	}

	public void setValidFlag(String validFlag) {
		set("valid_flag", validFlag);
	}
	
	public String getValidFlag() {
		return getStr("valid_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
