package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysEnummain<M extends BaseSysEnummain<M>> extends Model<M> implements IBean {

	public void setNo(String No) {
		set("No", No);
	}
	
	public String getNo() {
		return getStr("No");
	}

	public void setName(String Name) {
		set("Name", Name);
	}
	
	public String getName() {
		return getStr("Name");
	}

	public void setCfgVal(String CfgVal) {
		set("CfgVal", CfgVal);
	}
	
	public String getCfgVal() {
		return getStr("CfgVal");
	}

	public void setLang(String Lang) {
		set("Lang", Lang);
	}
	
	public String getLang() {
		return getStr("Lang");
	}

}
