package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountAgent<M extends BaseWxcmsAccountAgent<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setOpenId(String openId) {
		set("open_id", openId);
	}
	
	public String getOpenId() {
		return getStr("open_id");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public void setAgentNo(String agentNo) {
		set("agentNo", agentNo);
	}
	
	public String getAgentNo() {
		return getStr("agentNo");
	}

	public void setAgentStatus(Integer agentStatus) {
		set("agentStatus", agentStatus);
	}
	
	public Integer getAgentStatus() {
		return getInt("agentStatus");
	}

	public void setFormattedAddress(String formattedAddress) {
		set("formatted_address", formattedAddress);
	}
	
	public String getFormattedAddress() {
		return getStr("formatted_address");
	}

	public void setCountry(String country) {
		set("country", country);
	}
	
	public String getCountry() {
		return getStr("country");
	}

	public void setProvince(String province) {
		set("province", province);
	}
	
	public String getProvince() {
		return getStr("province");
	}

	public void setCity(String city) {
		set("city", city);
	}
	
	public String getCity() {
		return getStr("city");
	}

	public void setDistrict(String district) {
		set("district", district);
	}
	
	public String getDistrict() {
		return getStr("district");
	}

	public void setStreet(String street) {
		set("street", street);
	}
	
	public String getStreet() {
		return getStr("street");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIsValid(Integer isValid) {
		set("is_valid", isValid);
	}
	
	public Integer getIsValid() {
		return getInt("is_valid");
	}

}
