package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortEmp<M extends BasePortEmp<M>> extends Model<M> implements IBean {

	public void setNo(java.lang.String No) {
		set("No", No);
	}

	public java.lang.String getNo() {
		return getStr("No");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return getStr("Name");
	}

	public void setPass(java.lang.String Pass) {
		set("Pass", Pass);
	}

	public java.lang.String getPass() {
		return getStr("Pass");
	}

	public void setFkDept(java.lang.String fkDept) {
		set("FK_Dept", fkDept);
	}

	public java.lang.String getFkDept() {
		return getStr("FK_Dept");
	}

	public void setSID(java.lang.String SID) {
		set("SID", SID);
	}

	public java.lang.String getSID() {
		return getStr("SID");
	}

	public void setTel(java.lang.String Tel) {
		set("Tel", Tel);
	}

	public java.lang.String getTel() {
		return getStr("Tel");
	}

	public void setEmail(java.lang.String Email) {
		set("Email", Email);
	}

	public java.lang.String getEmail() {
		return getStr("Email");
	}

	public void setPinYin(java.lang.String PinYin) {
		set("PinYin", PinYin);
	}

	public java.lang.String getPinYin() {
		return getStr("PinYin");
	}

	public void setSignType(java.lang.Integer SignType) {
		set("SignType", SignType);
	}

	public java.lang.Integer getSignType() {
		return getInt("SignType");
	}

	public void setIdx(java.lang.Integer Idx) {
		set("Idx", Idx);
	}

	public java.lang.Integer getIdx() {
		return getInt("Idx");
	}

	public void setEmpNo(java.lang.String EmpNo) {
		set("EmpNo", EmpNo);
	}

	public java.lang.String getEmpNo() {
		return getStr("EmpNo");
	}

	public void setOrgNo(java.lang.String OrgNo) {
		set("OrgNo", OrgNo);
	}

	public java.lang.String getOrgNo() {
		return getStr("OrgNo");
	}

	public void setWxAppOpenId(java.lang.String WxAppOpenId) {
		set("WxAppOpenId", WxAppOpenId);
	}

	public java.lang.String getWxAppOpenId() {
		return getStr("WxAppOpenId");
	}

	public void setWxOpenId(java.lang.String WxOpenId) {
		set("WxOpenId", WxOpenId);
	}

	public java.lang.String getWxOpenId() {
		return getStr("WxOpenId");
	}

	public void setAccountType(java.lang.String accountType) {
		set("accountType", accountType);
	}

	public java.lang.String getAccountType() {
		return getStr("accountType");
	}

}
