package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityAddress<M extends BasePortActivityAddress<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setAddressData(String addressData) {
		set("address_data", addressData);
	}
	
	public String getAddressData() {
		return getStr("address_data");
	}

	public void setVisiable(String visiable) {
		set("visiable", visiable);
	}
	
	public String getVisiable() {
		return getStr("visiable");
	}

	public void setDealer(String dealer) {
		set("dealer", dealer);
	}
	
	public String getDealer() {
		return getStr("dealer");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setAddress(String address) {
		set("address", address);
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public void setLongitude(Float longitude) {
		set("longitude", longitude);
	}
	
	public Float getLongitude() {
		return getFloat("longitude");
	}

	public void setLatitude(Float latitude) {
		set("latitude", latitude);
	}
	
	public Float getLatitude() {
		return getFloat("latitude");
	}

}
