package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountAgentQrcode<M extends BaseWxcmsAccountAgentQrcode<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setAgentId(String agentId) {
		set("agent_id", agentId);
	}
	
	public String getAgentId() {
		return getStr("agent_id");
	}

	public void setQrcodeParam(String qrcodeParam) {
		set("qrcode_param", qrcodeParam);
	}
	
	public String getQrcodeParam() {
		return getStr("qrcode_param");
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
	}
	
	public String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
