package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityPlaybill<M extends BasePortActivityPlaybill<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setPbQrcode(String pbQrcode) {
		set("pb_qrcode", pbQrcode);
	}
	
	public String getPbQrcode() {
		return getStr("pb_qrcode");
	}

	public void setPbSourceOpenid(String pbSourceOpenid) {
		set("pb_source_openid", pbSourceOpenid);
	}
	
	public String getPbSourceOpenid() {
		return getStr("pb_source_openid");
	}

	public void setPbLeadingOpenid(String pbLeadingOpenid) {
		set("pb_leading_openid", pbLeadingOpenid);
	}
	
	public String getPbLeadingOpenid() {
		return getStr("pb_leading_openid");
	}

	public void setPbAcId(Integer pbAcId) {
		set("pb_ac_id", pbAcId);
	}
	
	public Integer getPbAcId() {
		return getInt("pb_ac_id");
	}

	public void setPbPlaybill(String pbPlaybill) {
		set("pb_playbill", pbPlaybill);
	}
	
	public String getPbPlaybill() {
		return getStr("pb_playbill");
	}

	public void setPbCrowd(String pbCrowd) {
		set("pb_crowd", pbCrowd);
	}
	
	public String getPbCrowd() {
		return getStr("pb_crowd");
	}

	public void setPbCrowdName(String pbCrowdName) {
		set("pb_crowd_name", pbCrowdName);
	}
	
	public String getPbCrowdName() {
		return getStr("pb_crowd_name");
	}

}
