package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityHelper<M extends BasePortActivityHelper<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setShareId(Integer shareId) {
		set("shareId", shareId);
	}
	
	public Integer getShareId() {
		return getInt("shareId");
	}

	public void setHelperAppOpenId(String helperAppOpenId) {
		set("helperAppOpenId", helperAppOpenId);
	}
	
	public String getHelperAppOpenId() {
		return getStr("helperAppOpenId");
	}

	public void setHelperOpenId(String helperOpenId) {
		set("helperOpenId", helperOpenId);
	}
	
	public String getHelperOpenId() {
		return getStr("helperOpenId");
	}

}
