package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegist<M extends BaseRegist<M>> extends Model<M> implements IBean {

	public void setMyPK(java.lang.String MyPK) {
		set("MyPK", MyPK);
	}

	public java.lang.String getMyPK() {
		return getStr("MyPK");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setAppOpenId(java.lang.String appOpenId) {
		set("appOpenId", appOpenId);
	}

	public java.lang.String getAppOpenId() {
		return getStr("appOpenId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setParentNo(java.lang.String parentNo) {
		set("parentNo", parentNo);
	}

	public java.lang.String getParentNo() {
		return getStr("parentNo");
	}

}
