package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxcmsAccountShopQrcode<M extends BaseWxcmsAccountShopQrcode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setShopid(Long shopid) {
		set("shopid", shopid);
	}
	
	public Long getShopid() {
		return getLong("shopid");
	}

	public void setQrcodeParam(String qrcodeParam) {
		set("qrcode_param", qrcodeParam);
	}
	
	public String getQrcodeParam() {
		return getStr("qrcode_param");
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
	}
	
	public String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

}
