package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortEmpRelation<M extends BasePortEmpRelation<M>> extends Model<M> implements IBean {

	public void setOID(Integer OID) {
		set("OID", OID);
	}
	
	public Integer getOID() {
		return getInt("OID");
	}

	public void setFkNo(String fkNo) {
		set("FK_No", fkNo);
	}
	
	public String getFkNo() {
		return getStr("FK_No");
	}

	public void setParentNo(String ParentNo) {
		set("ParentNo", ParentNo);
	}
	
	public String getParentNo() {
		return getStr("ParentNo");
	}

}
