package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortDept<M extends BasePortDept<M>> extends Model<M> implements IBean {

	public void setNo(java.lang.String No) {
		set("No", No);
	}

	public java.lang.String getNo() {
		return getStr("No");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return getStr("Name");
	}

	public void setNameOfPath(java.lang.String NameOfPath) {
		set("NameOfPath", NameOfPath);
	}

	public java.lang.String getNameOfPath() {
		return getStr("NameOfPath");
	}

	public void setParentNo(java.lang.String ParentNo) {
		set("ParentNo", ParentNo);
	}

	public java.lang.String getParentNo() {
		return getStr("ParentNo");
	}

	public void setIdx(java.lang.Integer Idx) {
		set("Idx", Idx);
	}

	public java.lang.Integer getIdx() {
		return getInt("Idx");
	}

	public void setOrgNo(java.lang.String OrgNo) {
		set("OrgNo", OrgNo);
	}

	public java.lang.String getOrgNo() {
		return getStr("OrgNo");
	}

	public void setT100Code(java.lang.String t100Code) {
		set("t100_code", t100Code);
	}

	public java.lang.String getT100Code() {
		return getStr("t100_code");
	}

}
