package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysSftable<M extends BaseSysSftable<M>> extends Model<M> implements IBean {

	public void setNo(String No) {
		set("No", No);
	}
	
	public String getNo() {
		return getStr("No");
	}

	public void setName(String Name) {
		set("Name", Name);
	}
	
	public String getName() {
		return getStr("Name");
	}

	public void setSrcType(Integer SrcType) {
		set("SrcType", SrcType);
	}
	
	public Integer getSrcType() {
		return getInt("SrcType");
	}

	public void setCodeStruct(Integer CodeStruct) {
		set("CodeStruct", CodeStruct);
	}
	
	public Integer getCodeStruct() {
		return getInt("CodeStruct");
	}

	public void setFkVal(String fkVal) {
		set("FK_Val", fkVal);
	}
	
	public String getFkVal() {
		return getStr("FK_Val");
	}

	public void setTableDesc(String TableDesc) {
		set("TableDesc", TableDesc);
	}
	
	public String getTableDesc() {
		return getStr("TableDesc");
	}

	public void setDefVal(String DefVal) {
		set("DefVal", DefVal);
	}
	
	public String getDefVal() {
		return getStr("DefVal");
	}

	public void setFkSfdbsrc(String fkSfdbsrc) {
		set("FK_SFDBSrc", fkSfdbsrc);
	}
	
	public String getFkSfdbsrc() {
		return getStr("FK_SFDBSrc");
	}

	public void setSrcTable(String SrcTable) {
		set("SrcTable", SrcTable);
	}
	
	public String getSrcTable() {
		return getStr("SrcTable");
	}

	public void setColumnValue(String ColumnValue) {
		set("ColumnValue", ColumnValue);
	}
	
	public String getColumnValue() {
		return getStr("ColumnValue");
	}

	public void setColumnText(String ColumnText) {
		set("ColumnText", ColumnText);
	}
	
	public String getColumnText() {
		return getStr("ColumnText");
	}

	public void setParentValue(String ParentValue) {
		set("ParentValue", ParentValue);
	}
	
	public String getParentValue() {
		return getStr("ParentValue");
	}

	public void setSelectStatement(String SelectStatement) {
		set("SelectStatement", SelectStatement);
	}
	
	public String getSelectStatement() {
		return getStr("SelectStatement");
	}

	public void setRDT(String RDT) {
		set("RDT", RDT);
	}
	
	public String getRDT() {
		return getStr("RDT");
	}

	public void setRootVal(String RootVal) {
		set("RootVal", RootVal);
	}
	
	public String getRootVal() {
		return getStr("RootVal");
	}

}
