package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegist<M extends BaseRegist<M>> extends Model<M> implements IBean {

	public void setMyPK(String MyPK) {
		set("MyPK", MyPK);
	}
	
	public String getMyPK() {
		return getStr("MyPK");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public void setAppOpenId(java.lang.String appOpenId) {
		set("appOpenId", appOpenId);
	}

	public java.lang.String getAppOpenId() {
		return getStr("appOpenId");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

}
