package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivity<M extends BasePortActivity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAcName(java.lang.String acName) {
		set("ac_name", acName);
	}

	public java.lang.String getAcName() {
		return getStr("ac_name");
	}

	public void setAcDetail(java.lang.String acDetail) {
		set("ac_detail", acDetail);
	}

	public java.lang.String getAcDetail() {
		return getStr("ac_detail");
	}

	public void setAcPlaybillImg(java.lang.String acPlaybillImg) {
		set("ac_playbill_img", acPlaybillImg);
	}

	public java.lang.String getAcPlaybillImg() {
		return getStr("ac_playbill_img");
	}

}
