package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHrRegister<M extends BaseHrRegister<M>> extends Model<M> implements IBean {

	public void setOID(java.lang.Integer OID) {
		set("OID", OID);
	}

	public java.lang.Integer getOID() {
		return getInt("OID");
	}

	public void setRDT(java.lang.String RDT) {
		set("RDT", RDT);
	}

	public java.lang.String getRDT() {
		return getStr("RDT");
	}

	public void setTitle(java.lang.String Title) {
		set("Title", Title);
	}

	public java.lang.String getTitle() {
		return getStr("Title");
	}

	public void setFID(java.lang.Integer FID) {
		set("FID", FID);
	}

	public java.lang.Integer getFID() {
		return getInt("FID");
	}

	public void setCDT(java.lang.String CDT) {
		set("CDT", CDT);
	}

	public java.lang.String getCDT() {
		return getStr("CDT");
	}

	public void setRec(java.lang.String Rec) {
		set("Rec", Rec);
	}

	public java.lang.String getRec() {
		return getStr("Rec");
	}

	public void setEmps(java.lang.String Emps) {
		set("Emps", Emps);
	}

	public java.lang.String getEmps() {
		return getStr("Emps");
	}

	public void setFkDept(java.lang.String fkDept) {
		set("FK_Dept", fkDept);
	}

	public java.lang.String getFkDept() {
		return getStr("FK_Dept");
	}

	public void setFkNy(java.lang.String fkNy) {
		set("FK_NY", fkNy);
	}

	public java.lang.String getFkNy() {
		return getStr("FK_NY");
	}

	public void setMyNum(java.lang.Integer MyNum) {
		set("MyNum", MyNum);
	}

	public java.lang.Integer getMyNum() {
		return getInt("MyNum");
	}

	public void setPNodeID(java.lang.Integer PNodeID) {
		set("PNodeID", PNodeID);
	}

	public java.lang.Integer getPNodeID() {
		return getInt("PNodeID");
	}

	public void setGUID(java.lang.String GUID) {
		set("GUID", GUID);
	}

	public java.lang.String getGUID() {
		return getStr("GUID");
	}

	public void setPEmp(java.lang.String PEmp) {
		set("PEmp", PEmp);
	}

	public java.lang.String getPEmp() {
		return getStr("PEmp");
	}

	public void setPrjNo(java.lang.String PrjNo) {
		set("PrjNo", PrjNo);
	}

	public java.lang.String getPrjNo() {
		return getStr("PrjNo");
	}

	public void setAtPara(java.lang.String AtPara) {
		set("AtPara", AtPara);
	}

	public java.lang.String getAtPara() {
		return getStr("AtPara");
	}

	public void setBillNo(java.lang.String BillNo) {
		set("BillNo", BillNo);
	}

	public java.lang.String getBillNo() {
		return getStr("BillNo");
	}

	public void setPrjName(java.lang.String PrjName) {
		set("PrjName", PrjName);
	}

	public java.lang.String getPrjName() {
		return getStr("PrjName");
	}

	public void setFlowNote(java.lang.String FlowNote) {
		set("FlowNote", FlowNote);
	}

	public java.lang.String getFlowNote() {
		return getStr("FlowNote");
	}

	public void setWFSta(java.lang.Integer WFSta) {
		set("WFSta", WFSta);
	}

	public java.lang.Integer getWFSta() {
		return getInt("WFSta");
	}

	public void setPWorkID(java.lang.Integer PWorkID) {
		set("PWorkID", PWorkID);
	}

	public java.lang.Integer getPWorkID() {
		return getInt("PWorkID");
	}

	public void setFlowDaySpan(java.math.BigDecimal FlowDaySpan) {
		set("FlowDaySpan", FlowDaySpan);
	}

	public java.math.BigDecimal getFlowDaySpan() {
		return get("FlowDaySpan");
	}

	public void setFlowEndNode(java.lang.Integer FlowEndNode) {
		set("FlowEndNode", FlowEndNode);
	}

	public java.lang.Integer getFlowEndNode() {
		return getInt("FlowEndNode");
	}

	public void setFlowEnderRDT(java.lang.String FlowEnderRDT) {
		set("FlowEnderRDT", FlowEnderRDT);
	}

	public java.lang.String getFlowEnderRDT() {
		return getStr("FlowEnderRDT");
	}

	public void setFlowStartRDT(java.lang.String FlowStartRDT) {
		set("FlowStartRDT", FlowStartRDT);
	}

	public java.lang.String getFlowStartRDT() {
		return getStr("FlowStartRDT");
	}

	public void setPFlowNo(java.lang.String PFlowNo) {
		set("PFlowNo", PFlowNo);
	}

	public java.lang.String getPFlowNo() {
		return getStr("PFlowNo");
	}

	public void setFlowEmps(java.lang.String FlowEmps) {
		set("FlowEmps", FlowEmps);
	}

	public java.lang.String getFlowEmps() {
		return getStr("FlowEmps");
	}

	public void setWFState(java.lang.Integer WFState) {
		set("WFState", WFState);
	}

	public java.lang.Integer getWFState() {
		return getInt("WFState");
	}

	public void setFlowEnder(java.lang.String FlowEnder) {
		set("FlowEnder", FlowEnder);
	}

	public java.lang.String getFlowEnder() {
		return getStr("FlowEnder");
	}

	public void setFlowStarter(java.lang.String FlowStarter) {
		set("FlowStarter", FlowStarter);
	}

	public java.lang.String getFlowStarter() {
		return getStr("FlowStarter");
	}

	public void setShouJiHaoMa(java.lang.String ShouJiHaoMa) {
		set("ShouJiHaoMa", ShouJiHaoMa);
	}

	public java.lang.String getShouJiHaoMa() {
		return getStr("ShouJiHaoMa");
	}

	public void setXingMing(java.lang.String XingMing) {
		set("XingMing", XingMing);
	}

	public java.lang.String getXingMing() {
		return getStr("XingMing");
	}

	public void setAppOpenId(java.lang.String appOpenId) {
		set("appOpenId", appOpenId);
	}

	public java.lang.String getAppOpenId() {
		return getStr("appOpenId");
	}

	public void setLeiBie(java.lang.String LeiBie) {
		set("LeiBie", LeiBie);
	}

	public java.lang.String getLeiBie() {
		return getStr("LeiBie");
	}

	public void setParentNo(java.lang.String ParentNo) {
		set("ParentNo", ParentNo);
	}

	public java.lang.String getParentNo() {
		return getStr("ParentNo");
	}

}
