package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityEmp<M extends BasePortActivityEmp<M>> extends Model<M> implements IBean {

	public void setNo(String No) {
		set("No", No);
	}
	
	public String getNo() {
		return getStr("No");
	}

	public void setName(String Name) {
		set("Name", Name);
	}
	
	public String getName() {
		return getStr("Name");
	}

	public void setPass(String Pass) {
		set("Pass", Pass);
	}
	
	public String getPass() {
		return getStr("Pass");
	}

	public void setFkDept(String fkDept) {
		set("FK_Dept", fkDept);
	}
	
	public String getFkDept() {
		return getStr("FK_Dept");
	}

	public void setSID(String SID) {
		set("SID", SID);
	}
	
	public String getSID() {
		return getStr("SID");
	}

	public void setTel(String Tel) {
		set("Tel", Tel);
	}
	
	public String getTel() {
		return getStr("Tel");
	}

	public void setEmail(String Email) {
		set("Email", Email);
	}
	
	public String getEmail() {
		return getStr("Email");
	}

	public void setPinYin(String PinYin) {
		set("PinYin", PinYin);
	}
	
	public String getPinYin() {
		return getStr("PinYin");
	}

	public void setSignType(Integer SignType) {
		set("SignType", SignType);
	}
	
	public Integer getSignType() {
		return getInt("SignType");
	}

	public void setIdx(Integer Idx) {
		set("Idx", Idx);
	}
	
	public Integer getIdx() {
		return getInt("Idx");
	}

	public void setEmpNo(String EmpNo) {
		set("EmpNo", EmpNo);
	}
	
	public String getEmpNo() {
		return getStr("EmpNo");
	}

	public void setOrgNo(String OrgNo) {
		set("OrgNo", OrgNo);
	}
	
	public String getOrgNo() {
		return getStr("OrgNo");
	}

	public void setWxAppOpenId(String WxAppOpenId) {
		set("WxAppOpenId", WxAppOpenId);
	}
	
	public String getWxAppOpenId() {
		return getStr("WxAppOpenId");
	}

	public void setWxOpenId(String WxOpenId) {
		set("WxOpenId", WxOpenId);
	}
	
	public String getWxOpenId() {
		return getStr("WxOpenId");
	}

	public void setAccountType(String accountType) {
		set("accountType", accountType);
	}
	
	public String getAccountType() {
		return getStr("accountType");
	}

	public void setYzjOpenId(String yzjOpenId) {
		set("yzjOpenId", yzjOpenId);
	}
	
	public String getYzjOpenId() {
		return getStr("yzjOpenId");
	}

	public void setYzjJobNo(String yzjJobNo) {
		set("yzjJobNo", yzjJobNo);
	}
	
	public String getYzjJobNo() {
		return getStr("yzjJobNo");
	}

	public void setZt(String zt) {
		set("zt", zt);
	}
	
	public String getZt() {
		return getStr("zt");
	}

}
