package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePortActivityAssist<M extends BasePortActivityAssist<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAsAcId(java.lang.Integer asAcId) {
		set("as_ac_id", asAcId);
	}

	public java.lang.Integer getAsAcId() {
		return getInt("as_ac_id");
	}

	public void setAsOpenid(java.lang.String asOpenid) {
		set("as_openid", asOpenid);
	}

	public java.lang.String getAsOpenid() {
		return getStr("as_openid");
	}

	public void setAsMobile(java.lang.String asMobile) {
		set("as_mobile", asMobile);
	}

	public java.lang.String getAsMobile() {
		return getStr("as_mobile");
	}

	public void setAsName(java.lang.String asName) {
		set("as_name", asName);
	}

	public java.lang.String getAsName() {
		return getStr("as_name");
	}

	public void setAsAddress(java.lang.String asAddress) {
		set("as_address", asAddress);
	}

	public java.lang.String getAsAddress() {
		return getStr("as_address");
	}

	public void setAsProductid(java.lang.String asProductid) {
		set("as_productid", asProductid);
	}

	public java.lang.String getAsProductid() {
		return getStr("as_productid");
	}

	public void setHelperInfo(java.lang.String helperInfo) {
		set("helperInfo", helperInfo);
	}

	public java.lang.String getHelperInfo() {
		return getStr("helperInfo");
	}

}
